// Code generated by Fern. DO NOT EDIT.

package chats

import (
	context "context"
	v505 "github.com/itrn0/server-sdk-go"
	core "github.com/itrn0/server-sdk-go/core"
	internal "github.com/itrn0/server-sdk-go/internal"
	option "github.com/itrn0/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	request *v505.ListChatsRequest,
	opts ...option.RequestOption,
) (*v505.ChatPaginatedResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new chat with optional SMS delivery via transport field. Requires at least one of: assistantId/assistant, sessionId, or previousChatId. Note: sessionId and previousChatId are mutually exclusive. Transport field enables SMS delivery with two modes: (1) New conversation - provide transport.phoneNumberId and transport.customer to create a new session, (2) Existing conversation - provide sessionId to use existing session data. Cannot specify both sessionId and transport fields together. The transport.useLLMGeneratedMessageForOutbound flag controls whether input is processed by LLM (true, default) or forwarded directly as SMS (false).
func (c *Client) Create(
	ctx context.Context,
	request *v505.CreateChatDto,
	opts ...option.RequestOption,
) (*v505.CreateChatsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	request *v505.GetChatsRequest,
	opts ...option.RequestOption,
) (*v505.Chat, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	request *v505.DeleteChatsRequest,
	opts ...option.RequestOption,
) (*v505.Chat, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateResponse(
	ctx context.Context,
	request *v505.OpenAiResponsesRequest,
	opts ...option.RequestOption,
) (*v505.CreateResponseChatsResponse, error) {
	response, err := c.WithRawResponse.CreateResponse(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
