// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/itrn0/server-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	createCampaignDtoFieldName          = big.NewInt(1 << 0)
	createCampaignDtoFieldAssistantId   = big.NewInt(1 << 1)
	createCampaignDtoFieldWorkflowId    = big.NewInt(1 << 2)
	createCampaignDtoFieldPhoneNumberId = big.NewInt(1 << 3)
	createCampaignDtoFieldSchedulePlan  = big.NewInt(1 << 4)
	createCampaignDtoFieldCustomers     = big.NewInt(1 << 5)
)

type CreateCampaignDto struct {
	// This is the name of the campaign. This is just for your own reference.
	Name string `json:"name" url:"-"`
	// This is the assistant ID that will be used for the campaign calls. Note: Either assistantId or workflowId can be used, but not both.
	AssistantId *string `json:"assistantId,omitempty" url:"-"`
	// This is the workflow ID that will be used for the campaign calls. Note: Either assistantId or workflowId can be used, but not both.
	WorkflowId *string `json:"workflowId,omitempty" url:"-"`
	// This is the phone number ID that will be used for the campaign calls.
	PhoneNumberId string `json:"phoneNumberId" url:"-"`
	// This is the schedule plan for the campaign. Calls will start at startedAt and continue until your organization’s concurrency limit is reached. Any remaining calls will be retried for up to one hour as capacity becomes available. After that hour or after latestAt, whichever comes first, any calls that couldn’t be placed won’t be retried.
	SchedulePlan *SchedulePlan `json:"schedulePlan,omitempty" url:"-"`
	// These are the customers that will be called in the campaign.
	Customers []*CreateCustomerDto `json:"customers,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateCampaignDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCampaignDto) SetName(name string) {
	c.Name = name
	c.require(createCampaignDtoFieldName)
}

// SetAssistantId sets the AssistantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCampaignDto) SetAssistantId(assistantId *string) {
	c.AssistantId = assistantId
	c.require(createCampaignDtoFieldAssistantId)
}

// SetWorkflowId sets the WorkflowId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCampaignDto) SetWorkflowId(workflowId *string) {
	c.WorkflowId = workflowId
	c.require(createCampaignDtoFieldWorkflowId)
}

// SetPhoneNumberId sets the PhoneNumberId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCampaignDto) SetPhoneNumberId(phoneNumberId string) {
	c.PhoneNumberId = phoneNumberId
	c.require(createCampaignDtoFieldPhoneNumberId)
}

// SetSchedulePlan sets the SchedulePlan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCampaignDto) SetSchedulePlan(schedulePlan *SchedulePlan) {
	c.SchedulePlan = schedulePlan
	c.require(createCampaignDtoFieldSchedulePlan)
}

// SetCustomers sets the Customers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCampaignDto) SetCustomers(customers []*CreateCustomerDto) {
	c.Customers = customers
	c.require(createCampaignDtoFieldCustomers)
}

var (
	campaignControllerFindAllRequestFieldId          = big.NewInt(1 << 0)
	campaignControllerFindAllRequestFieldStatus      = big.NewInt(1 << 1)
	campaignControllerFindAllRequestFieldPage        = big.NewInt(1 << 2)
	campaignControllerFindAllRequestFieldSortOrder   = big.NewInt(1 << 3)
	campaignControllerFindAllRequestFieldLimit       = big.NewInt(1 << 4)
	campaignControllerFindAllRequestFieldCreatedAtGt = big.NewInt(1 << 5)
	campaignControllerFindAllRequestFieldCreatedAtLt = big.NewInt(1 << 6)
	campaignControllerFindAllRequestFieldCreatedAtGe = big.NewInt(1 << 7)
	campaignControllerFindAllRequestFieldCreatedAtLe = big.NewInt(1 << 8)
	campaignControllerFindAllRequestFieldUpdatedAtGt = big.NewInt(1 << 9)
	campaignControllerFindAllRequestFieldUpdatedAtLt = big.NewInt(1 << 10)
	campaignControllerFindAllRequestFieldUpdatedAtGe = big.NewInt(1 << 11)
	campaignControllerFindAllRequestFieldUpdatedAtLe = big.NewInt(1 << 12)
)

type CampaignControllerFindAllRequest struct {
	Id     *string                                 `json:"-" url:"id,omitempty"`
	Status *CampaignControllerFindAllRequestStatus `json:"-" url:"status,omitempty"`
	// This is the page number to return. Defaults to 1.
	Page *float64 `json:"-" url:"page,omitempty"`
	// This is the sort order for pagination. Defaults to 'DESC'.
	SortOrder *CampaignControllerFindAllRequestSortOrder `json:"-" url:"sortOrder,omitempty"`
	// This is the maximum number of items to return. Defaults to 100.
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// This will return items where the createdAt is greater than the specified value.
	CreatedAtGt *time.Time `json:"-" url:"createdAtGt,omitempty"`
	// This will return items where the createdAt is less than the specified value.
	CreatedAtLt *time.Time `json:"-" url:"createdAtLt,omitempty"`
	// This will return items where the createdAt is greater than or equal to the specified value.
	CreatedAtGe *time.Time `json:"-" url:"createdAtGe,omitempty"`
	// This will return items where the createdAt is less than or equal to the specified value.
	CreatedAtLe *time.Time `json:"-" url:"createdAtLe,omitempty"`
	// This will return items where the updatedAt is greater than the specified value.
	UpdatedAtGt *time.Time `json:"-" url:"updatedAtGt,omitempty"`
	// This will return items where the updatedAt is less than the specified value.
	UpdatedAtLt *time.Time `json:"-" url:"updatedAtLt,omitempty"`
	// This will return items where the updatedAt is greater than or equal to the specified value.
	UpdatedAtGe *time.Time `json:"-" url:"updatedAtGe,omitempty"`
	// This will return items where the updatedAt is less than or equal to the specified value.
	UpdatedAtLe *time.Time `json:"-" url:"updatedAtLe,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CampaignControllerFindAllRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetId(id *string) {
	c.Id = id
	c.require(campaignControllerFindAllRequestFieldId)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetStatus(status *CampaignControllerFindAllRequestStatus) {
	c.Status = status
	c.require(campaignControllerFindAllRequestFieldStatus)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetPage(page *float64) {
	c.Page = page
	c.require(campaignControllerFindAllRequestFieldPage)
}

// SetSortOrder sets the SortOrder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetSortOrder(sortOrder *CampaignControllerFindAllRequestSortOrder) {
	c.SortOrder = sortOrder
	c.require(campaignControllerFindAllRequestFieldSortOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetLimit(limit *float64) {
	c.Limit = limit
	c.require(campaignControllerFindAllRequestFieldLimit)
}

// SetCreatedAtGt sets the CreatedAtGt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetCreatedAtGt(createdAtGt *time.Time) {
	c.CreatedAtGt = createdAtGt
	c.require(campaignControllerFindAllRequestFieldCreatedAtGt)
}

// SetCreatedAtLt sets the CreatedAtLt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetCreatedAtLt(createdAtLt *time.Time) {
	c.CreatedAtLt = createdAtLt
	c.require(campaignControllerFindAllRequestFieldCreatedAtLt)
}

// SetCreatedAtGe sets the CreatedAtGe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetCreatedAtGe(createdAtGe *time.Time) {
	c.CreatedAtGe = createdAtGe
	c.require(campaignControllerFindAllRequestFieldCreatedAtGe)
}

// SetCreatedAtLe sets the CreatedAtLe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetCreatedAtLe(createdAtLe *time.Time) {
	c.CreatedAtLe = createdAtLe
	c.require(campaignControllerFindAllRequestFieldCreatedAtLe)
}

// SetUpdatedAtGt sets the UpdatedAtGt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetUpdatedAtGt(updatedAtGt *time.Time) {
	c.UpdatedAtGt = updatedAtGt
	c.require(campaignControllerFindAllRequestFieldUpdatedAtGt)
}

// SetUpdatedAtLt sets the UpdatedAtLt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetUpdatedAtLt(updatedAtLt *time.Time) {
	c.UpdatedAtLt = updatedAtLt
	c.require(campaignControllerFindAllRequestFieldUpdatedAtLt)
}

// SetUpdatedAtGe sets the UpdatedAtGe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetUpdatedAtGe(updatedAtGe *time.Time) {
	c.UpdatedAtGe = updatedAtGe
	c.require(campaignControllerFindAllRequestFieldUpdatedAtGe)
}

// SetUpdatedAtLe sets the UpdatedAtLe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindAllRequest) SetUpdatedAtLe(updatedAtLe *time.Time) {
	c.UpdatedAtLe = updatedAtLe
	c.require(campaignControllerFindAllRequestFieldUpdatedAtLe)
}

var (
	campaignControllerFindOneRequestFieldId = big.NewInt(1 << 0)
)

type CampaignControllerFindOneRequest struct {
	Id string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CampaignControllerFindOneRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerFindOneRequest) SetId(id string) {
	c.Id = id
	c.require(campaignControllerFindOneRequestFieldId)
}

var (
	campaignControllerRemoveRequestFieldId = big.NewInt(1 << 0)
)

type CampaignControllerRemoveRequest struct {
	Id string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CampaignControllerRemoveRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignControllerRemoveRequest) SetId(id string) {
	c.Id = id
	c.require(campaignControllerRemoveRequestFieldId)
}

var (
	updateCampaignDtoFieldId            = big.NewInt(1 << 0)
	updateCampaignDtoFieldName          = big.NewInt(1 << 1)
	updateCampaignDtoFieldAssistantId   = big.NewInt(1 << 2)
	updateCampaignDtoFieldWorkflowId    = big.NewInt(1 << 3)
	updateCampaignDtoFieldPhoneNumberId = big.NewInt(1 << 4)
	updateCampaignDtoFieldSchedulePlan  = big.NewInt(1 << 5)
	updateCampaignDtoFieldStatus        = big.NewInt(1 << 6)
)

type UpdateCampaignDto struct {
	Id string `json:"-" url:"-"`
	// This is the name of the campaign. This is just for your own reference.
	Name *string `json:"name,omitempty" url:"-"`
	// This is the assistant ID that will be used for the campaign calls.
	// Can only be updated if campaign is not in progress or has ended.
	AssistantId *string `json:"assistantId,omitempty" url:"-"`
	// This is the workflow ID that will be used for the campaign calls.
	// Can only be updated if campaign is not in progress or has ended.
	WorkflowId *string `json:"workflowId,omitempty" url:"-"`
	// This is the phone number ID that will be used for the campaign calls.
	// Can only be updated if campaign is not in progress or has ended.
	PhoneNumberId *string `json:"phoneNumberId,omitempty" url:"-"`
	// This is the schedule plan for the campaign.
	// Can only be updated if campaign is not in progress or has ended.
	SchedulePlan *SchedulePlan `json:"schedulePlan,omitempty" url:"-"`
	// This is the status of the campaign.
	// Can only be updated to 'ended' if you want to end the campaign.
	// When set to 'ended', it will delete all scheduled calls. Calls in progress will be allowed to complete.
	Status *UpdateCampaignDtoStatus `json:"status,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateCampaignDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetId(id string) {
	u.Id = id
	u.require(updateCampaignDtoFieldId)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetName(name *string) {
	u.Name = name
	u.require(updateCampaignDtoFieldName)
}

// SetAssistantId sets the AssistantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetAssistantId(assistantId *string) {
	u.AssistantId = assistantId
	u.require(updateCampaignDtoFieldAssistantId)
}

// SetWorkflowId sets the WorkflowId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetWorkflowId(workflowId *string) {
	u.WorkflowId = workflowId
	u.require(updateCampaignDtoFieldWorkflowId)
}

// SetPhoneNumberId sets the PhoneNumberId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetPhoneNumberId(phoneNumberId *string) {
	u.PhoneNumberId = phoneNumberId
	u.require(updateCampaignDtoFieldPhoneNumberId)
}

// SetSchedulePlan sets the SchedulePlan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetSchedulePlan(schedulePlan *SchedulePlan) {
	u.SchedulePlan = schedulePlan
	u.require(updateCampaignDtoFieldSchedulePlan)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCampaignDto) SetStatus(status *UpdateCampaignDtoStatus) {
	u.Status = status
	u.require(updateCampaignDtoFieldStatus)
}

var (
	campaignFieldStatus                     = big.NewInt(1 << 0)
	campaignFieldEndedReason                = big.NewInt(1 << 1)
	campaignFieldName                       = big.NewInt(1 << 2)
	campaignFieldAssistantId                = big.NewInt(1 << 3)
	campaignFieldWorkflowId                 = big.NewInt(1 << 4)
	campaignFieldPhoneNumberId              = big.NewInt(1 << 5)
	campaignFieldSchedulePlan               = big.NewInt(1 << 6)
	campaignFieldCustomers                  = big.NewInt(1 << 7)
	campaignFieldId                         = big.NewInt(1 << 8)
	campaignFieldOrgId                      = big.NewInt(1 << 9)
	campaignFieldCreatedAt                  = big.NewInt(1 << 10)
	campaignFieldUpdatedAt                  = big.NewInt(1 << 11)
	campaignFieldCalls                      = big.NewInt(1 << 12)
	campaignFieldCallsCounterScheduled      = big.NewInt(1 << 13)
	campaignFieldCallsCounterQueued         = big.NewInt(1 << 14)
	campaignFieldCallsCounterInProgress     = big.NewInt(1 << 15)
	campaignFieldCallsCounterEndedVoicemail = big.NewInt(1 << 16)
	campaignFieldCallsCounterEnded          = big.NewInt(1 << 17)
)

type Campaign struct {
	// This is the status of the campaign.
	Status CampaignStatus `json:"status" url:"status"`
	// This is the explanation for how the campaign ended.
	EndedReason *CampaignEndedReason `json:"endedReason,omitempty" url:"endedReason,omitempty"`
	// This is the name of the campaign. This is just for your own reference.
	Name string `json:"name" url:"name"`
	// This is the assistant ID that will be used for the campaign calls. Note: Either assistantId or workflowId can be used, but not both.
	AssistantId *string `json:"assistantId,omitempty" url:"assistantId,omitempty"`
	// This is the workflow ID that will be used for the campaign calls. Note: Either assistantId or workflowId can be used, but not both.
	WorkflowId *string `json:"workflowId,omitempty" url:"workflowId,omitempty"`
	// This is the phone number ID that will be used for the campaign calls.
	PhoneNumberId string `json:"phoneNumberId" url:"phoneNumberId"`
	// This is the schedule plan for the campaign. Calls will start at startedAt and continue until your organization’s concurrency limit is reached. Any remaining calls will be retried for up to one hour as capacity becomes available. After that hour or after latestAt, whichever comes first, any calls that couldn’t be placed won’t be retried.
	SchedulePlan *SchedulePlan `json:"schedulePlan,omitempty" url:"schedulePlan,omitempty"`
	// These are the customers that will be called in the campaign.
	Customers []*CreateCustomerDto `json:"customers" url:"customers"`
	// This is the unique identifier for the campaign.
	Id string `json:"id" url:"id"`
	// This is the unique identifier for the org that this campaign belongs to.
	OrgId string `json:"orgId" url:"orgId"`
	// This is the ISO 8601 date-time string of when the campaign was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// This is the ISO 8601 date-time string of when the campaign was last updated.
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	// This is a map of call IDs to campaign call details.
	Calls map[string]interface{} `json:"calls" url:"calls"`
	// This is the number of calls that have been scheduled.
	CallsCounterScheduled float64 `json:"callsCounterScheduled" url:"callsCounterScheduled"`
	// This is the number of calls that have been queued.
	CallsCounterQueued float64 `json:"callsCounterQueued" url:"callsCounterQueued"`
	// This is the number of calls that have been in progress.
	CallsCounterInProgress float64 `json:"callsCounterInProgress" url:"callsCounterInProgress"`
	// This is the number of calls whose ended reason is 'voicemail'.
	CallsCounterEndedVoicemail float64 `json:"callsCounterEndedVoicemail" url:"callsCounterEndedVoicemail"`
	// This is the number of calls that have ended.
	CallsCounterEnded float64 `json:"callsCounterEnded" url:"callsCounterEnded"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Campaign) GetStatus() CampaignStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *Campaign) GetEndedReason() *CampaignEndedReason {
	if c == nil {
		return nil
	}
	return c.EndedReason
}

func (c *Campaign) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Campaign) GetAssistantId() *string {
	if c == nil {
		return nil
	}
	return c.AssistantId
}

func (c *Campaign) GetWorkflowId() *string {
	if c == nil {
		return nil
	}
	return c.WorkflowId
}

func (c *Campaign) GetPhoneNumberId() string {
	if c == nil {
		return ""
	}
	return c.PhoneNumberId
}

func (c *Campaign) GetSchedulePlan() *SchedulePlan {
	if c == nil {
		return nil
	}
	return c.SchedulePlan
}

func (c *Campaign) GetCustomers() []*CreateCustomerDto {
	if c == nil {
		return nil
	}
	return c.Customers
}

func (c *Campaign) GetId() string {
	if c == nil {
		return ""
	}
	return c.Id
}

func (c *Campaign) GetOrgId() string {
	if c == nil {
		return ""
	}
	return c.OrgId
}

func (c *Campaign) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Campaign) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Campaign) GetCalls() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Calls
}

func (c *Campaign) GetCallsCounterScheduled() float64 {
	if c == nil {
		return 0
	}
	return c.CallsCounterScheduled
}

func (c *Campaign) GetCallsCounterQueued() float64 {
	if c == nil {
		return 0
	}
	return c.CallsCounterQueued
}

func (c *Campaign) GetCallsCounterInProgress() float64 {
	if c == nil {
		return 0
	}
	return c.CallsCounterInProgress
}

func (c *Campaign) GetCallsCounterEndedVoicemail() float64 {
	if c == nil {
		return 0
	}
	return c.CallsCounterEndedVoicemail
}

func (c *Campaign) GetCallsCounterEnded() float64 {
	if c == nil {
		return 0
	}
	return c.CallsCounterEnded
}

func (c *Campaign) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *Campaign) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetStatus(status CampaignStatus) {
	c.Status = status
	c.require(campaignFieldStatus)
}

// SetEndedReason sets the EndedReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetEndedReason(endedReason *CampaignEndedReason) {
	c.EndedReason = endedReason
	c.require(campaignFieldEndedReason)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetName(name string) {
	c.Name = name
	c.require(campaignFieldName)
}

// SetAssistantId sets the AssistantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetAssistantId(assistantId *string) {
	c.AssistantId = assistantId
	c.require(campaignFieldAssistantId)
}

// SetWorkflowId sets the WorkflowId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetWorkflowId(workflowId *string) {
	c.WorkflowId = workflowId
	c.require(campaignFieldWorkflowId)
}

// SetPhoneNumberId sets the PhoneNumberId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetPhoneNumberId(phoneNumberId string) {
	c.PhoneNumberId = phoneNumberId
	c.require(campaignFieldPhoneNumberId)
}

// SetSchedulePlan sets the SchedulePlan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetSchedulePlan(schedulePlan *SchedulePlan) {
	c.SchedulePlan = schedulePlan
	c.require(campaignFieldSchedulePlan)
}

// SetCustomers sets the Customers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCustomers(customers []*CreateCustomerDto) {
	c.Customers = customers
	c.require(campaignFieldCustomers)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetId(id string) {
	c.Id = id
	c.require(campaignFieldId)
}

// SetOrgId sets the OrgId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetOrgId(orgId string) {
	c.OrgId = orgId
	c.require(campaignFieldOrgId)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(campaignFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(campaignFieldUpdatedAt)
}

// SetCalls sets the Calls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCalls(calls map[string]interface{}) {
	c.Calls = calls
	c.require(campaignFieldCalls)
}

// SetCallsCounterScheduled sets the CallsCounterScheduled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCallsCounterScheduled(callsCounterScheduled float64) {
	c.CallsCounterScheduled = callsCounterScheduled
	c.require(campaignFieldCallsCounterScheduled)
}

// SetCallsCounterQueued sets the CallsCounterQueued field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCallsCounterQueued(callsCounterQueued float64) {
	c.CallsCounterQueued = callsCounterQueued
	c.require(campaignFieldCallsCounterQueued)
}

// SetCallsCounterInProgress sets the CallsCounterInProgress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCallsCounterInProgress(callsCounterInProgress float64) {
	c.CallsCounterInProgress = callsCounterInProgress
	c.require(campaignFieldCallsCounterInProgress)
}

// SetCallsCounterEndedVoicemail sets the CallsCounterEndedVoicemail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCallsCounterEndedVoicemail(callsCounterEndedVoicemail float64) {
	c.CallsCounterEndedVoicemail = callsCounterEndedVoicemail
	c.require(campaignFieldCallsCounterEndedVoicemail)
}

// SetCallsCounterEnded sets the CallsCounterEnded field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Campaign) SetCallsCounterEnded(callsCounterEnded float64) {
	c.CallsCounterEnded = callsCounterEnded
	c.require(campaignFieldCallsCounterEnded)
}

func (c *Campaign) UnmarshalJSON(data []byte) error {
	type embed Campaign
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = Campaign(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Campaign) MarshalJSON() ([]byte, error) {
	type embed Campaign
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Campaign) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// This is the explanation for how the campaign ended.
type CampaignEndedReason string

const (
	CampaignEndedReasonCampaignScheduledEndedByUser  CampaignEndedReason = "campaign.scheduled.ended-by-user"
	CampaignEndedReasonCampaignInProgressEndedByUser CampaignEndedReason = "campaign.in-progress.ended-by-user"
	CampaignEndedReasonCampaignEndedSuccess          CampaignEndedReason = "campaign.ended.success"
)

func NewCampaignEndedReasonFromString(s string) (CampaignEndedReason, error) {
	switch s {
	case "campaign.scheduled.ended-by-user":
		return CampaignEndedReasonCampaignScheduledEndedByUser, nil
	case "campaign.in-progress.ended-by-user":
		return CampaignEndedReasonCampaignInProgressEndedByUser, nil
	case "campaign.ended.success":
		return CampaignEndedReasonCampaignEndedSuccess, nil
	}
	var t CampaignEndedReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CampaignEndedReason) Ptr() *CampaignEndedReason {
	return &c
}

var (
	campaignPaginatedResponseFieldResults  = big.NewInt(1 << 0)
	campaignPaginatedResponseFieldMetadata = big.NewInt(1 << 1)
)

type CampaignPaginatedResponse struct {
	Results  []*Campaign     `json:"results" url:"results"`
	Metadata *PaginationMeta `json:"metadata" url:"metadata"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CampaignPaginatedResponse) GetResults() []*Campaign {
	if c == nil {
		return nil
	}
	return c.Results
}

func (c *CampaignPaginatedResponse) GetMetadata() *PaginationMeta {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CampaignPaginatedResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CampaignPaginatedResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignPaginatedResponse) SetResults(results []*Campaign) {
	c.Results = results
	c.require(campaignPaginatedResponseFieldResults)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CampaignPaginatedResponse) SetMetadata(metadata *PaginationMeta) {
	c.Metadata = metadata
	c.require(campaignPaginatedResponseFieldMetadata)
}

func (c *CampaignPaginatedResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CampaignPaginatedResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CampaignPaginatedResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CampaignPaginatedResponse) MarshalJSON() ([]byte, error) {
	type embed CampaignPaginatedResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CampaignPaginatedResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// This is the status of the campaign.
type CampaignStatus string

const (
	CampaignStatusScheduled  CampaignStatus = "scheduled"
	CampaignStatusInProgress CampaignStatus = "in-progress"
	CampaignStatusEnded      CampaignStatus = "ended"
)

func NewCampaignStatusFromString(s string) (CampaignStatus, error) {
	switch s {
	case "scheduled":
		return CampaignStatusScheduled, nil
	case "in-progress":
		return CampaignStatusInProgress, nil
	case "ended":
		return CampaignStatusEnded, nil
	}
	var t CampaignStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CampaignStatus) Ptr() *CampaignStatus {
	return &c
}

type CampaignControllerFindAllRequestSortOrder string

const (
	CampaignControllerFindAllRequestSortOrderAsc  CampaignControllerFindAllRequestSortOrder = "ASC"
	CampaignControllerFindAllRequestSortOrderDesc CampaignControllerFindAllRequestSortOrder = "DESC"
)

func NewCampaignControllerFindAllRequestSortOrderFromString(s string) (CampaignControllerFindAllRequestSortOrder, error) {
	switch s {
	case "ASC":
		return CampaignControllerFindAllRequestSortOrderAsc, nil
	case "DESC":
		return CampaignControllerFindAllRequestSortOrderDesc, nil
	}
	var t CampaignControllerFindAllRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CampaignControllerFindAllRequestSortOrder) Ptr() *CampaignControllerFindAllRequestSortOrder {
	return &c
}

type CampaignControllerFindAllRequestStatus string

const (
	CampaignControllerFindAllRequestStatusScheduled  CampaignControllerFindAllRequestStatus = "scheduled"
	CampaignControllerFindAllRequestStatusInProgress CampaignControllerFindAllRequestStatus = "in-progress"
	CampaignControllerFindAllRequestStatusEnded      CampaignControllerFindAllRequestStatus = "ended"
)

func NewCampaignControllerFindAllRequestStatusFromString(s string) (CampaignControllerFindAllRequestStatus, error) {
	switch s {
	case "scheduled":
		return CampaignControllerFindAllRequestStatusScheduled, nil
	case "in-progress":
		return CampaignControllerFindAllRequestStatusInProgress, nil
	case "ended":
		return CampaignControllerFindAllRequestStatusEnded, nil
	}
	var t CampaignControllerFindAllRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CampaignControllerFindAllRequestStatus) Ptr() *CampaignControllerFindAllRequestStatus {
	return &c
}

// This is the status of the campaign.
// Can only be updated to 'ended' if you want to end the campaign.
// When set to 'ended', it will delete all scheduled calls. Calls in progress will be allowed to complete.
type UpdateCampaignDtoStatus string

const (
	UpdateCampaignDtoStatusEnded UpdateCampaignDtoStatus = "ended"
)

func NewUpdateCampaignDtoStatusFromString(s string) (UpdateCampaignDtoStatus, error) {
	switch s {
	case "ended":
		return UpdateCampaignDtoStatusEnded, nil
	}
	var t UpdateCampaignDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateCampaignDtoStatus) Ptr() *UpdateCampaignDtoStatus {
	return &u
}
