// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/itrn0/server-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	providerResourceControllerCreateProviderResourceRequestFieldProvider     = big.NewInt(1 << 0)
	providerResourceControllerCreateProviderResourceRequestFieldResourceName = big.NewInt(1 << 1)
)

type ProviderResourceControllerCreateProviderResourceRequest struct {
	// The provider (e.g., 11labs)
	Provider ProviderResourceControllerCreateProviderResourceRequestProvider `json:"-" url:"-"`
	// The resource name (e.g., pronunciation-dictionary)
	ResourceName ProviderResourceControllerCreateProviderResourceRequestResourceName `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderResourceControllerCreateProviderResourceRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerCreateProviderResourceRequest) SetProvider(provider ProviderResourceControllerCreateProviderResourceRequestProvider) {
	p.Provider = provider
	p.require(providerResourceControllerCreateProviderResourceRequestFieldProvider)
}

// SetResourceName sets the ResourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerCreateProviderResourceRequest) SetResourceName(resourceName ProviderResourceControllerCreateProviderResourceRequestResourceName) {
	p.ResourceName = resourceName
	p.require(providerResourceControllerCreateProviderResourceRequestFieldResourceName)
}

var (
	providerResourceControllerDeleteProviderResourceRequestFieldProvider     = big.NewInt(1 << 0)
	providerResourceControllerDeleteProviderResourceRequestFieldResourceName = big.NewInt(1 << 1)
	providerResourceControllerDeleteProviderResourceRequestFieldId           = big.NewInt(1 << 2)
)

type ProviderResourceControllerDeleteProviderResourceRequest struct {
	// The provider (e.g., 11labs)
	Provider ProviderResourceControllerDeleteProviderResourceRequestProvider `json:"-" url:"-"`
	// The resource name (e.g., pronunciation-dictionary)
	ResourceName ProviderResourceControllerDeleteProviderResourceRequestResourceName `json:"-" url:"-"`
	Id           string                                                              `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderResourceControllerDeleteProviderResourceRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerDeleteProviderResourceRequest) SetProvider(provider ProviderResourceControllerDeleteProviderResourceRequestProvider) {
	p.Provider = provider
	p.require(providerResourceControllerDeleteProviderResourceRequestFieldProvider)
}

// SetResourceName sets the ResourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerDeleteProviderResourceRequest) SetResourceName(resourceName ProviderResourceControllerDeleteProviderResourceRequestResourceName) {
	p.ResourceName = resourceName
	p.require(providerResourceControllerDeleteProviderResourceRequestFieldResourceName)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerDeleteProviderResourceRequest) SetId(id string) {
	p.Id = id
	p.require(providerResourceControllerDeleteProviderResourceRequestFieldId)
}

var (
	providerResourceControllerGetProviderResourceRequestFieldProvider     = big.NewInt(1 << 0)
	providerResourceControllerGetProviderResourceRequestFieldResourceName = big.NewInt(1 << 1)
	providerResourceControllerGetProviderResourceRequestFieldId           = big.NewInt(1 << 2)
)

type ProviderResourceControllerGetProviderResourceRequest struct {
	// The provider (e.g., 11labs)
	Provider ProviderResourceControllerGetProviderResourceRequestProvider `json:"-" url:"-"`
	// The resource name (e.g., pronunciation-dictionary)
	ResourceName ProviderResourceControllerGetProviderResourceRequestResourceName `json:"-" url:"-"`
	Id           string                                                           `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderResourceControllerGetProviderResourceRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourceRequest) SetProvider(provider ProviderResourceControllerGetProviderResourceRequestProvider) {
	p.Provider = provider
	p.require(providerResourceControllerGetProviderResourceRequestFieldProvider)
}

// SetResourceName sets the ResourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourceRequest) SetResourceName(resourceName ProviderResourceControllerGetProviderResourceRequestResourceName) {
	p.ResourceName = resourceName
	p.require(providerResourceControllerGetProviderResourceRequestFieldResourceName)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourceRequest) SetId(id string) {
	p.Id = id
	p.require(providerResourceControllerGetProviderResourceRequestFieldId)
}

var (
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldProvider     = big.NewInt(1 << 0)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldResourceName = big.NewInt(1 << 1)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldId           = big.NewInt(1 << 2)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldResourceId   = big.NewInt(1 << 3)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldPage         = big.NewInt(1 << 4)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldSortOrder    = big.NewInt(1 << 5)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldLimit        = big.NewInt(1 << 6)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtGt  = big.NewInt(1 << 7)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtLt  = big.NewInt(1 << 8)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtGe  = big.NewInt(1 << 9)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtLe  = big.NewInt(1 << 10)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtGt  = big.NewInt(1 << 11)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtLt  = big.NewInt(1 << 12)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtGe  = big.NewInt(1 << 13)
	providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtLe  = big.NewInt(1 << 14)
)

type ProviderResourceControllerGetProviderResourcesPaginatedRequest struct {
	// The provider (e.g., 11labs)
	Provider ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider `json:"-" url:"-"`
	// The resource name (e.g., pronunciation-dictionary)
	ResourceName ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName `json:"-" url:"-"`
	Id           *string                                                                    `json:"-" url:"id,omitempty"`
	ResourceId   *string                                                                    `json:"-" url:"resourceId,omitempty"`
	// This is the page number to return. Defaults to 1.
	Page *float64 `json:"-" url:"page,omitempty"`
	// This is the sort order for pagination. Defaults to 'DESC'.
	SortOrder *ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder `json:"-" url:"sortOrder,omitempty"`
	// This is the maximum number of items to return. Defaults to 100.
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// This will return items where the createdAt is greater than the specified value.
	CreatedAtGt *time.Time `json:"-" url:"createdAtGt,omitempty"`
	// This will return items where the createdAt is less than the specified value.
	CreatedAtLt *time.Time `json:"-" url:"createdAtLt,omitempty"`
	// This will return items where the createdAt is greater than or equal to the specified value.
	CreatedAtGe *time.Time `json:"-" url:"createdAtGe,omitempty"`
	// This will return items where the createdAt is less than or equal to the specified value.
	CreatedAtLe *time.Time `json:"-" url:"createdAtLe,omitempty"`
	// This will return items where the updatedAt is greater than the specified value.
	UpdatedAtGt *time.Time `json:"-" url:"updatedAtGt,omitempty"`
	// This will return items where the updatedAt is less than the specified value.
	UpdatedAtLt *time.Time `json:"-" url:"updatedAtLt,omitempty"`
	// This will return items where the updatedAt is greater than or equal to the specified value.
	UpdatedAtGe *time.Time `json:"-" url:"updatedAtGe,omitempty"`
	// This will return items where the updatedAt is less than or equal to the specified value.
	UpdatedAtLe *time.Time `json:"-" url:"updatedAtLe,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetProvider(provider ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider) {
	p.Provider = provider
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldProvider)
}

// SetResourceName sets the ResourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetResourceName(resourceName ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName) {
	p.ResourceName = resourceName
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldResourceName)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetId(id *string) {
	p.Id = id
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldId)
}

// SetResourceId sets the ResourceId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetResourceId(resourceId *string) {
	p.ResourceId = resourceId
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldResourceId)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetPage(page *float64) {
	p.Page = page
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldPage)
}

// SetSortOrder sets the SortOrder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetSortOrder(sortOrder *ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder) {
	p.SortOrder = sortOrder
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldSortOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetLimit(limit *float64) {
	p.Limit = limit
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldLimit)
}

// SetCreatedAtGt sets the CreatedAtGt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetCreatedAtGt(createdAtGt *time.Time) {
	p.CreatedAtGt = createdAtGt
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtGt)
}

// SetCreatedAtLt sets the CreatedAtLt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetCreatedAtLt(createdAtLt *time.Time) {
	p.CreatedAtLt = createdAtLt
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtLt)
}

// SetCreatedAtGe sets the CreatedAtGe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetCreatedAtGe(createdAtGe *time.Time) {
	p.CreatedAtGe = createdAtGe
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtGe)
}

// SetCreatedAtLe sets the CreatedAtLe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetCreatedAtLe(createdAtLe *time.Time) {
	p.CreatedAtLe = createdAtLe
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldCreatedAtLe)
}

// SetUpdatedAtGt sets the UpdatedAtGt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetUpdatedAtGt(updatedAtGt *time.Time) {
	p.UpdatedAtGt = updatedAtGt
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtGt)
}

// SetUpdatedAtLt sets the UpdatedAtLt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetUpdatedAtLt(updatedAtLt *time.Time) {
	p.UpdatedAtLt = updatedAtLt
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtLt)
}

// SetUpdatedAtGe sets the UpdatedAtGe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetUpdatedAtGe(updatedAtGe *time.Time) {
	p.UpdatedAtGe = updatedAtGe
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtGe)
}

// SetUpdatedAtLe sets the UpdatedAtLe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerGetProviderResourcesPaginatedRequest) SetUpdatedAtLe(updatedAtLe *time.Time) {
	p.UpdatedAtLe = updatedAtLe
	p.require(providerResourceControllerGetProviderResourcesPaginatedRequestFieldUpdatedAtLe)
}

var (
	providerResourceControllerUpdateProviderResourceRequestFieldProvider     = big.NewInt(1 << 0)
	providerResourceControllerUpdateProviderResourceRequestFieldResourceName = big.NewInt(1 << 1)
	providerResourceControllerUpdateProviderResourceRequestFieldId           = big.NewInt(1 << 2)
)

type ProviderResourceControllerUpdateProviderResourceRequest struct {
	// The provider (e.g., 11labs)
	Provider ProviderResourceControllerUpdateProviderResourceRequestProvider `json:"-" url:"-"`
	// The resource name (e.g., pronunciation-dictionary)
	ResourceName ProviderResourceControllerUpdateProviderResourceRequestResourceName `json:"-" url:"-"`
	Id           string                                                              `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderResourceControllerUpdateProviderResourceRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerUpdateProviderResourceRequest) SetProvider(provider ProviderResourceControllerUpdateProviderResourceRequestProvider) {
	p.Provider = provider
	p.require(providerResourceControllerUpdateProviderResourceRequestFieldProvider)
}

// SetResourceName sets the ResourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerUpdateProviderResourceRequest) SetResourceName(resourceName ProviderResourceControllerUpdateProviderResourceRequestResourceName) {
	p.ResourceName = resourceName
	p.require(providerResourceControllerUpdateProviderResourceRequestFieldResourceName)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourceControllerUpdateProviderResourceRequest) SetId(id string) {
	p.Id = id
	p.require(providerResourceControllerUpdateProviderResourceRequestFieldId)
}

var (
	elevenLabsPronunciationDictionaryFieldPronunciationDictionaryId = big.NewInt(1 << 0)
	elevenLabsPronunciationDictionaryFieldDictionaryName            = big.NewInt(1 << 1)
	elevenLabsPronunciationDictionaryFieldCreatedBy                 = big.NewInt(1 << 2)
	elevenLabsPronunciationDictionaryFieldCreationTimeUnix          = big.NewInt(1 << 3)
	elevenLabsPronunciationDictionaryFieldVersionId                 = big.NewInt(1 << 4)
	elevenLabsPronunciationDictionaryFieldVersionRulesNum           = big.NewInt(1 << 5)
	elevenLabsPronunciationDictionaryFieldPermissionOnResource      = big.NewInt(1 << 6)
	elevenLabsPronunciationDictionaryFieldDescription               = big.NewInt(1 << 7)
)

type ElevenLabsPronunciationDictionary struct {
	// The ID of the pronunciation dictionary
	PronunciationDictionaryId string `json:"pronunciationDictionaryId" url:"pronunciationDictionaryId"`
	// The name of the pronunciation dictionary
	DictionaryName string `json:"dictionaryName" url:"dictionaryName"`
	// The user ID of the creator
	CreatedBy string `json:"createdBy" url:"createdBy"`
	// The creation time in Unix timestamp
	CreationTimeUnix float64 `json:"creationTimeUnix" url:"creationTimeUnix"`
	// The version ID of the pronunciation dictionary
	VersionId string `json:"versionId" url:"versionId"`
	// The number of rules in this version
	VersionRulesNum float64 `json:"versionRulesNum" url:"versionRulesNum"`
	// The permission level on this resource
	PermissionOnResource *ElevenLabsPronunciationDictionaryPermissionOnResource `json:"permissionOnResource,omitempty" url:"permissionOnResource,omitempty"`
	// The description of the pronunciation dictionary
	Description *string `json:"description,omitempty" url:"description,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ElevenLabsPronunciationDictionary) GetPronunciationDictionaryId() string {
	if e == nil {
		return ""
	}
	return e.PronunciationDictionaryId
}

func (e *ElevenLabsPronunciationDictionary) GetDictionaryName() string {
	if e == nil {
		return ""
	}
	return e.DictionaryName
}

func (e *ElevenLabsPronunciationDictionary) GetCreatedBy() string {
	if e == nil {
		return ""
	}
	return e.CreatedBy
}

func (e *ElevenLabsPronunciationDictionary) GetCreationTimeUnix() float64 {
	if e == nil {
		return 0
	}
	return e.CreationTimeUnix
}

func (e *ElevenLabsPronunciationDictionary) GetVersionId() string {
	if e == nil {
		return ""
	}
	return e.VersionId
}

func (e *ElevenLabsPronunciationDictionary) GetVersionRulesNum() float64 {
	if e == nil {
		return 0
	}
	return e.VersionRulesNum
}

func (e *ElevenLabsPronunciationDictionary) GetPermissionOnResource() *ElevenLabsPronunciationDictionaryPermissionOnResource {
	if e == nil {
		return nil
	}
	return e.PermissionOnResource
}

func (e *ElevenLabsPronunciationDictionary) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *ElevenLabsPronunciationDictionary) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ElevenLabsPronunciationDictionary) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetPronunciationDictionaryId sets the PronunciationDictionaryId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetPronunciationDictionaryId(pronunciationDictionaryId string) {
	e.PronunciationDictionaryId = pronunciationDictionaryId
	e.require(elevenLabsPronunciationDictionaryFieldPronunciationDictionaryId)
}

// SetDictionaryName sets the DictionaryName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetDictionaryName(dictionaryName string) {
	e.DictionaryName = dictionaryName
	e.require(elevenLabsPronunciationDictionaryFieldDictionaryName)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetCreatedBy(createdBy string) {
	e.CreatedBy = createdBy
	e.require(elevenLabsPronunciationDictionaryFieldCreatedBy)
}

// SetCreationTimeUnix sets the CreationTimeUnix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetCreationTimeUnix(creationTimeUnix float64) {
	e.CreationTimeUnix = creationTimeUnix
	e.require(elevenLabsPronunciationDictionaryFieldCreationTimeUnix)
}

// SetVersionId sets the VersionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetVersionId(versionId string) {
	e.VersionId = versionId
	e.require(elevenLabsPronunciationDictionaryFieldVersionId)
}

// SetVersionRulesNum sets the VersionRulesNum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetVersionRulesNum(versionRulesNum float64) {
	e.VersionRulesNum = versionRulesNum
	e.require(elevenLabsPronunciationDictionaryFieldVersionRulesNum)
}

// SetPermissionOnResource sets the PermissionOnResource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetPermissionOnResource(permissionOnResource *ElevenLabsPronunciationDictionaryPermissionOnResource) {
	e.PermissionOnResource = permissionOnResource
	e.require(elevenLabsPronunciationDictionaryFieldPermissionOnResource)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ElevenLabsPronunciationDictionary) SetDescription(description *string) {
	e.Description = description
	e.require(elevenLabsPronunciationDictionaryFieldDescription)
}

func (e *ElevenLabsPronunciationDictionary) UnmarshalJSON(data []byte) error {
	type unmarshaler ElevenLabsPronunciationDictionary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ElevenLabsPronunciationDictionary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ElevenLabsPronunciationDictionary) MarshalJSON() ([]byte, error) {
	type embed ElevenLabsPronunciationDictionary
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ElevenLabsPronunciationDictionary) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// The permission level on this resource
type ElevenLabsPronunciationDictionaryPermissionOnResource string

const (
	ElevenLabsPronunciationDictionaryPermissionOnResourceAdmin  ElevenLabsPronunciationDictionaryPermissionOnResource = "admin"
	ElevenLabsPronunciationDictionaryPermissionOnResourceEditor ElevenLabsPronunciationDictionaryPermissionOnResource = "editor"
	ElevenLabsPronunciationDictionaryPermissionOnResourceViewer ElevenLabsPronunciationDictionaryPermissionOnResource = "viewer"
)

func NewElevenLabsPronunciationDictionaryPermissionOnResourceFromString(s string) (ElevenLabsPronunciationDictionaryPermissionOnResource, error) {
	switch s {
	case "admin":
		return ElevenLabsPronunciationDictionaryPermissionOnResourceAdmin, nil
	case "editor":
		return ElevenLabsPronunciationDictionaryPermissionOnResourceEditor, nil
	case "viewer":
		return ElevenLabsPronunciationDictionaryPermissionOnResourceViewer, nil
	}
	var t ElevenLabsPronunciationDictionaryPermissionOnResource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ElevenLabsPronunciationDictionaryPermissionOnResource) Ptr() *ElevenLabsPronunciationDictionaryPermissionOnResource {
	return &e
}

var (
	providerResourceFieldId           = big.NewInt(1 << 0)
	providerResourceFieldOrgId        = big.NewInt(1 << 1)
	providerResourceFieldCreatedAt    = big.NewInt(1 << 2)
	providerResourceFieldUpdatedAt    = big.NewInt(1 << 3)
	providerResourceFieldProvider     = big.NewInt(1 << 4)
	providerResourceFieldResourceName = big.NewInt(1 << 5)
	providerResourceFieldResourceId   = big.NewInt(1 << 6)
	providerResourceFieldResource     = big.NewInt(1 << 7)
)

type ProviderResource struct {
	// This is the unique identifier for the provider resource.
	Id string `json:"id" url:"id"`
	// This is the unique identifier for the org that this provider resource belongs to.
	OrgId string `json:"orgId" url:"orgId"`
	// This is the ISO 8601 date-time string of when the provider resource was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// This is the ISO 8601 date-time string of when the provider resource was last updated.
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	// This is the provider that manages this resource.
	Provider ProviderResourceProvider `json:"provider" url:"provider"`
	// This is the name/type of the resource.
	ResourceName ProviderResourceResourceName `json:"resourceName" url:"resourceName"`
	// This is the provider-specific identifier for the resource.
	ResourceId string `json:"resourceId" url:"resourceId"`
	// This is the full resource data from the provider's API.
	Resource *ElevenLabsPronunciationDictionary `json:"resource" url:"resource"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderResource) GetId() string {
	if p == nil {
		return ""
	}
	return p.Id
}

func (p *ProviderResource) GetOrgId() string {
	if p == nil {
		return ""
	}
	return p.OrgId
}

func (p *ProviderResource) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *ProviderResource) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *ProviderResource) GetProvider() ProviderResourceProvider {
	if p == nil {
		return ""
	}
	return p.Provider
}

func (p *ProviderResource) GetResourceName() ProviderResourceResourceName {
	if p == nil {
		return ""
	}
	return p.ResourceName
}

func (p *ProviderResource) GetResourceId() string {
	if p == nil {
		return ""
	}
	return p.ResourceId
}

func (p *ProviderResource) GetResource() *ElevenLabsPronunciationDictionary {
	if p == nil {
		return nil
	}
	return p.Resource
}

func (p *ProviderResource) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *ProviderResource) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetId(id string) {
	p.Id = id
	p.require(providerResourceFieldId)
}

// SetOrgId sets the OrgId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetOrgId(orgId string) {
	p.OrgId = orgId
	p.require(providerResourceFieldOrgId)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetCreatedAt(createdAt time.Time) {
	p.CreatedAt = createdAt
	p.require(providerResourceFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetUpdatedAt(updatedAt time.Time) {
	p.UpdatedAt = updatedAt
	p.require(providerResourceFieldUpdatedAt)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetProvider(provider ProviderResourceProvider) {
	p.Provider = provider
	p.require(providerResourceFieldProvider)
}

// SetResourceName sets the ResourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetResourceName(resourceName ProviderResourceResourceName) {
	p.ResourceName = resourceName
	p.require(providerResourceFieldResourceName)
}

// SetResourceId sets the ResourceId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetResourceId(resourceId string) {
	p.ResourceId = resourceId
	p.require(providerResourceFieldResourceId)
}

// SetResource sets the Resource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResource) SetResource(resource *ElevenLabsPronunciationDictionary) {
	p.Resource = resource
	p.require(providerResourceFieldResource)
}

func (p *ProviderResource) UnmarshalJSON(data []byte) error {
	type embed ProviderResource
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = ProviderResource(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	p.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderResource) MarshalJSON() ([]byte, error) {
	type embed ProviderResource
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*p),
		CreatedAt: internal.NewDateTime(p.CreatedAt),
		UpdatedAt: internal.NewDateTime(p.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderResource) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	providerResourcePaginatedResponseFieldResults  = big.NewInt(1 << 0)
	providerResourcePaginatedResponseFieldMetadata = big.NewInt(1 << 1)
)

type ProviderResourcePaginatedResponse struct {
	Results  []*ProviderResource `json:"results" url:"results"`
	Metadata *PaginationMeta     `json:"metadata" url:"metadata"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderResourcePaginatedResponse) GetResults() []*ProviderResource {
	if p == nil {
		return nil
	}
	return p.Results
}

func (p *ProviderResourcePaginatedResponse) GetMetadata() *PaginationMeta {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *ProviderResourcePaginatedResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *ProviderResourcePaginatedResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourcePaginatedResponse) SetResults(results []*ProviderResource) {
	p.Results = results
	p.require(providerResourcePaginatedResponseFieldResults)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderResourcePaginatedResponse) SetMetadata(metadata *PaginationMeta) {
	p.Metadata = metadata
	p.require(providerResourcePaginatedResponseFieldMetadata)
}

func (p *ProviderResourcePaginatedResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderResourcePaginatedResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderResourcePaginatedResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderResourcePaginatedResponse) MarshalJSON() ([]byte, error) {
	type embed ProviderResourcePaginatedResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderResourcePaginatedResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// This is the provider that manages this resource.
type ProviderResourceProvider string

const (
	ProviderResourceProviderElevenLabs ProviderResourceProvider = "11labs"
)

func NewProviderResourceProviderFromString(s string) (ProviderResourceProvider, error) {
	switch s {
	case "11labs":
		return ProviderResourceProviderElevenLabs, nil
	}
	var t ProviderResourceProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceProvider) Ptr() *ProviderResourceProvider {
	return &p
}

// This is the name/type of the resource.
type ProviderResourceResourceName string

const (
	ProviderResourceResourceNamePronunciationDictionary ProviderResourceResourceName = "pronunciation-dictionary"
)

func NewProviderResourceResourceNameFromString(s string) (ProviderResourceResourceName, error) {
	switch s {
	case "pronunciation-dictionary":
		return ProviderResourceResourceNamePronunciationDictionary, nil
	}
	var t ProviderResourceResourceName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceResourceName) Ptr() *ProviderResourceResourceName {
	return &p
}

type ProviderResourceControllerCreateProviderResourceRequestProvider string

const (
	ProviderResourceControllerCreateProviderResourceRequestProviderElevenLabs ProviderResourceControllerCreateProviderResourceRequestProvider = "11labs"
)

func NewProviderResourceControllerCreateProviderResourceRequestProviderFromString(s string) (ProviderResourceControllerCreateProviderResourceRequestProvider, error) {
	switch s {
	case "11labs":
		return ProviderResourceControllerCreateProviderResourceRequestProviderElevenLabs, nil
	}
	var t ProviderResourceControllerCreateProviderResourceRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerCreateProviderResourceRequestProvider) Ptr() *ProviderResourceControllerCreateProviderResourceRequestProvider {
	return &p
}

type ProviderResourceControllerCreateProviderResourceRequestResourceName string

const (
	ProviderResourceControllerCreateProviderResourceRequestResourceNamePronunciationDictionary ProviderResourceControllerCreateProviderResourceRequestResourceName = "pronunciation-dictionary"
)

func NewProviderResourceControllerCreateProviderResourceRequestResourceNameFromString(s string) (ProviderResourceControllerCreateProviderResourceRequestResourceName, error) {
	switch s {
	case "pronunciation-dictionary":
		return ProviderResourceControllerCreateProviderResourceRequestResourceNamePronunciationDictionary, nil
	}
	var t ProviderResourceControllerCreateProviderResourceRequestResourceName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerCreateProviderResourceRequestResourceName) Ptr() *ProviderResourceControllerCreateProviderResourceRequestResourceName {
	return &p
}

type ProviderResourceControllerDeleteProviderResourceRequestProvider string

const (
	ProviderResourceControllerDeleteProviderResourceRequestProviderElevenLabs ProviderResourceControllerDeleteProviderResourceRequestProvider = "11labs"
)

func NewProviderResourceControllerDeleteProviderResourceRequestProviderFromString(s string) (ProviderResourceControllerDeleteProviderResourceRequestProvider, error) {
	switch s {
	case "11labs":
		return ProviderResourceControllerDeleteProviderResourceRequestProviderElevenLabs, nil
	}
	var t ProviderResourceControllerDeleteProviderResourceRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerDeleteProviderResourceRequestProvider) Ptr() *ProviderResourceControllerDeleteProviderResourceRequestProvider {
	return &p
}

type ProviderResourceControllerDeleteProviderResourceRequestResourceName string

const (
	ProviderResourceControllerDeleteProviderResourceRequestResourceNamePronunciationDictionary ProviderResourceControllerDeleteProviderResourceRequestResourceName = "pronunciation-dictionary"
)

func NewProviderResourceControllerDeleteProviderResourceRequestResourceNameFromString(s string) (ProviderResourceControllerDeleteProviderResourceRequestResourceName, error) {
	switch s {
	case "pronunciation-dictionary":
		return ProviderResourceControllerDeleteProviderResourceRequestResourceNamePronunciationDictionary, nil
	}
	var t ProviderResourceControllerDeleteProviderResourceRequestResourceName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerDeleteProviderResourceRequestResourceName) Ptr() *ProviderResourceControllerDeleteProviderResourceRequestResourceName {
	return &p
}

type ProviderResourceControllerGetProviderResourceRequestProvider string

const (
	ProviderResourceControllerGetProviderResourceRequestProviderElevenLabs ProviderResourceControllerGetProviderResourceRequestProvider = "11labs"
)

func NewProviderResourceControllerGetProviderResourceRequestProviderFromString(s string) (ProviderResourceControllerGetProviderResourceRequestProvider, error) {
	switch s {
	case "11labs":
		return ProviderResourceControllerGetProviderResourceRequestProviderElevenLabs, nil
	}
	var t ProviderResourceControllerGetProviderResourceRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerGetProviderResourceRequestProvider) Ptr() *ProviderResourceControllerGetProviderResourceRequestProvider {
	return &p
}

type ProviderResourceControllerGetProviderResourceRequestResourceName string

const (
	ProviderResourceControllerGetProviderResourceRequestResourceNamePronunciationDictionary ProviderResourceControllerGetProviderResourceRequestResourceName = "pronunciation-dictionary"
)

func NewProviderResourceControllerGetProviderResourceRequestResourceNameFromString(s string) (ProviderResourceControllerGetProviderResourceRequestResourceName, error) {
	switch s {
	case "pronunciation-dictionary":
		return ProviderResourceControllerGetProviderResourceRequestResourceNamePronunciationDictionary, nil
	}
	var t ProviderResourceControllerGetProviderResourceRequestResourceName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerGetProviderResourceRequestResourceName) Ptr() *ProviderResourceControllerGetProviderResourceRequestResourceName {
	return &p
}

type ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider string

const (
	ProviderResourceControllerGetProviderResourcesPaginatedRequestProviderElevenLabs ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider = "11labs"
)

func NewProviderResourceControllerGetProviderResourcesPaginatedRequestProviderFromString(s string) (ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider, error) {
	switch s {
	case "11labs":
		return ProviderResourceControllerGetProviderResourcesPaginatedRequestProviderElevenLabs, nil
	}
	var t ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider) Ptr() *ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider {
	return &p
}

type ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName string

const (
	ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceNamePronunciationDictionary ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName = "pronunciation-dictionary"
)

func NewProviderResourceControllerGetProviderResourcesPaginatedRequestResourceNameFromString(s string) (ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName, error) {
	switch s {
	case "pronunciation-dictionary":
		return ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceNamePronunciationDictionary, nil
	}
	var t ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName) Ptr() *ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName {
	return &p
}

type ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder string

const (
	ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderAsc  ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder = "ASC"
	ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderDesc ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder = "DESC"
)

func NewProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderFromString(s string) (ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder, error) {
	switch s {
	case "ASC":
		return ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderAsc, nil
	case "DESC":
		return ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderDesc, nil
	}
	var t ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder) Ptr() *ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder {
	return &p
}

type ProviderResourceControllerUpdateProviderResourceRequestProvider string

const (
	ProviderResourceControllerUpdateProviderResourceRequestProviderElevenLabs ProviderResourceControllerUpdateProviderResourceRequestProvider = "11labs"
)

func NewProviderResourceControllerUpdateProviderResourceRequestProviderFromString(s string) (ProviderResourceControllerUpdateProviderResourceRequestProvider, error) {
	switch s {
	case "11labs":
		return ProviderResourceControllerUpdateProviderResourceRequestProviderElevenLabs, nil
	}
	var t ProviderResourceControllerUpdateProviderResourceRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerUpdateProviderResourceRequestProvider) Ptr() *ProviderResourceControllerUpdateProviderResourceRequestProvider {
	return &p
}

type ProviderResourceControllerUpdateProviderResourceRequestResourceName string

const (
	ProviderResourceControllerUpdateProviderResourceRequestResourceNamePronunciationDictionary ProviderResourceControllerUpdateProviderResourceRequestResourceName = "pronunciation-dictionary"
)

func NewProviderResourceControllerUpdateProviderResourceRequestResourceNameFromString(s string) (ProviderResourceControllerUpdateProviderResourceRequestResourceName, error) {
	switch s {
	case "pronunciation-dictionary":
		return ProviderResourceControllerUpdateProviderResourceRequestResourceNamePronunciationDictionary, nil
	}
	var t ProviderResourceControllerUpdateProviderResourceRequestResourceName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderResourceControllerUpdateProviderResourceRequestResourceName) Ptr() *ProviderResourceControllerUpdateProviderResourceRequestResourceName {
	return &p
}
