// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/itrn0/server-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	createSessionDtoFieldName              = big.NewInt(1 << 0)
	createSessionDtoFieldStatus            = big.NewInt(1 << 1)
	createSessionDtoFieldExpirationSeconds = big.NewInt(1 << 2)
	createSessionDtoFieldAssistantId       = big.NewInt(1 << 3)
	createSessionDtoFieldAssistant         = big.NewInt(1 << 4)
	createSessionDtoFieldSquadId           = big.NewInt(1 << 5)
	createSessionDtoFieldSquad             = big.NewInt(1 << 6)
	createSessionDtoFieldMessages          = big.NewInt(1 << 7)
	createSessionDtoFieldCustomer          = big.NewInt(1 << 8)
	createSessionDtoFieldPhoneNumberId     = big.NewInt(1 << 9)
	createSessionDtoFieldPhoneNumber       = big.NewInt(1 << 10)
)

type CreateSessionDto struct {
	// This is a user-defined name for the session. Maximum length is 40 characters.
	Name *string `json:"name,omitempty" url:"-"`
	// This is the current status of the session. Can be either 'active' or 'completed'.
	Status *CreateSessionDtoStatus `json:"status,omitempty" url:"-"`
	// Session expiration time in seconds. Defaults to 24 hours (86400 seconds) if not set.
	ExpirationSeconds *float64 `json:"expirationSeconds,omitempty" url:"-"`
	// This is the ID of the assistant associated with this session. Use this when referencing an existing assistant.
	AssistantId *string `json:"assistantId,omitempty" url:"-"`
	// This is the assistant configuration for this session. Use this when creating a new assistant configuration.
	// If assistantId is provided, this will be ignored.
	Assistant *CreateAssistantDto `json:"assistant,omitempty" url:"-"`
	// This is the squad ID associated with this session. Use this when referencing an existing squad.
	SquadId *string `json:"squadId,omitempty" url:"-"`
	// This is the squad configuration for this session. Use this when creating a new squad configuration.
	// If squadId is provided, this will be ignored.
	Squad *CreateSquadDto `json:"squad,omitempty" url:"-"`
	// This is an array of chat messages in the session.
	Messages []*CreateSessionDtoMessagesItem `json:"messages,omitempty" url:"-"`
	// This is the customer information associated with this session.
	Customer *CreateCustomerDto `json:"customer,omitempty" url:"-"`
	// This is the ID of the phone number associated with this session.
	PhoneNumberId *string `json:"phoneNumberId,omitempty" url:"-"`
	// This is the phone number configuration for this session.
	PhoneNumber *ImportTwilioPhoneNumberDto `json:"phoneNumber,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSessionDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetName(name *string) {
	c.Name = name
	c.require(createSessionDtoFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetStatus(status *CreateSessionDtoStatus) {
	c.Status = status
	c.require(createSessionDtoFieldStatus)
}

// SetExpirationSeconds sets the ExpirationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetExpirationSeconds(expirationSeconds *float64) {
	c.ExpirationSeconds = expirationSeconds
	c.require(createSessionDtoFieldExpirationSeconds)
}

// SetAssistantId sets the AssistantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetAssistantId(assistantId *string) {
	c.AssistantId = assistantId
	c.require(createSessionDtoFieldAssistantId)
}

// SetAssistant sets the Assistant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetAssistant(assistant *CreateAssistantDto) {
	c.Assistant = assistant
	c.require(createSessionDtoFieldAssistant)
}

// SetSquadId sets the SquadId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetSquadId(squadId *string) {
	c.SquadId = squadId
	c.require(createSessionDtoFieldSquadId)
}

// SetSquad sets the Squad field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetSquad(squad *CreateSquadDto) {
	c.Squad = squad
	c.require(createSessionDtoFieldSquad)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetMessages(messages []*CreateSessionDtoMessagesItem) {
	c.Messages = messages
	c.require(createSessionDtoFieldMessages)
}

// SetCustomer sets the Customer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetCustomer(customer *CreateCustomerDto) {
	c.Customer = customer
	c.require(createSessionDtoFieldCustomer)
}

// SetPhoneNumberId sets the PhoneNumberId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetPhoneNumberId(phoneNumberId *string) {
	c.PhoneNumberId = phoneNumberId
	c.require(createSessionDtoFieldPhoneNumberId)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionDto) SetPhoneNumber(phoneNumber *ImportTwilioPhoneNumberDto) {
	c.PhoneNumber = phoneNumber
	c.require(createSessionDtoFieldPhoneNumber)
}

var (
	deleteSessionsRequestFieldId = big.NewInt(1 << 0)
)

type DeleteSessionsRequest struct {
	Id string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSessionsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionsRequest) SetId(id string) {
	d.Id = id
	d.require(deleteSessionsRequestFieldId)
}

var (
	getSessionsRequestFieldId = big.NewInt(1 << 0)
)

type GetSessionsRequest struct {
	Id string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSessionsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionsRequest) SetId(id string) {
	g.Id = id
	g.require(getSessionsRequestFieldId)
}

var (
	listSessionsRequestFieldName                   = big.NewInt(1 << 0)
	listSessionsRequestFieldAssistantId            = big.NewInt(1 << 1)
	listSessionsRequestFieldSquadId                = big.NewInt(1 << 2)
	listSessionsRequestFieldWorkflowId             = big.NewInt(1 << 3)
	listSessionsRequestFieldNumberE164CheckEnabled = big.NewInt(1 << 4)
	listSessionsRequestFieldExtension              = big.NewInt(1 << 5)
	listSessionsRequestFieldAssistantOverrides     = big.NewInt(1 << 6)
	listSessionsRequestFieldNumber                 = big.NewInt(1 << 7)
	listSessionsRequestFieldSipUri                 = big.NewInt(1 << 8)
	listSessionsRequestFieldEmail                  = big.NewInt(1 << 9)
	listSessionsRequestFieldExternalId             = big.NewInt(1 << 10)
	listSessionsRequestFieldPage                   = big.NewInt(1 << 11)
	listSessionsRequestFieldSortOrder              = big.NewInt(1 << 12)
	listSessionsRequestFieldLimit                  = big.NewInt(1 << 13)
	listSessionsRequestFieldCreatedAtGt            = big.NewInt(1 << 14)
	listSessionsRequestFieldCreatedAtLt            = big.NewInt(1 << 15)
	listSessionsRequestFieldCreatedAtGe            = big.NewInt(1 << 16)
	listSessionsRequestFieldCreatedAtLe            = big.NewInt(1 << 17)
	listSessionsRequestFieldUpdatedAtGt            = big.NewInt(1 << 18)
	listSessionsRequestFieldUpdatedAtLt            = big.NewInt(1 << 19)
	listSessionsRequestFieldUpdatedAtGe            = big.NewInt(1 << 20)
	listSessionsRequestFieldUpdatedAtLe            = big.NewInt(1 << 21)
)

type ListSessionsRequest struct {
	// This is the name of the customer. This is just for your own reference.
	//
	// For SIP inbound calls, this is extracted from the `From` SIP header with format `"Display Name" <sip:username@domain>`.
	Name *string `json:"-" url:"name,omitempty"`
	// This is the ID of the assistant to filter sessions by.
	AssistantId *string `json:"-" url:"assistantId,omitempty"`
	// This is the ID of the squad to filter sessions by.
	SquadId *string `json:"-" url:"squadId,omitempty"`
	// This is the ID of the workflow to filter sessions by.
	WorkflowId *string `json:"-" url:"workflowId,omitempty"`
	// This is the flag to toggle the E164 check for the `number` field. This is an advanced property which should be used if you know your use case requires it.
	//
	// Use cases:
	// - `false`: To allow non-E164 numbers like `+001234567890`, `1234`, or `abc`. This is useful for dialing out to non-E164 numbers on your SIP trunks.
	// - `true` (default): To allow only E164 numbers like `+14155551234`. This is standard for PSTN calls.
	//
	// If `false`, the `number` is still required to only contain alphanumeric characters (regex: `/^\+?[a-zA-Z0-9]+$/`).
	//
	// @default true (E164 check is enabled)
	NumberE164CheckEnabled *bool `json:"-" url:"numberE164CheckEnabled,omitempty"`
	// This is the extension that will be dialed after the call is answered.
	Extension *string `json:"-" url:"extension,omitempty"`
	// These are the overrides for the assistant's settings and template variables specific to this customer.
	// This allows customization of the assistant's behavior for individual customers in batch calls.
	AssistantOverrides *string `json:"-" url:"assistantOverrides,omitempty"`
	// This is the number of the customer.
	Number *string `json:"-" url:"number,omitempty"`
	// This is the SIP URI of the customer.
	SipUri *string `json:"-" url:"sipUri,omitempty"`
	// This is the email of the customer.
	Email *string `json:"-" url:"email,omitempty"`
	// This is the external ID of the customer.
	ExternalId *string `json:"-" url:"externalId,omitempty"`
	// This is the page number to return. Defaults to 1.
	Page *float64 `json:"-" url:"page,omitempty"`
	// This is the sort order for pagination. Defaults to 'DESC'.
	SortOrder *ListSessionsRequestSortOrder `json:"-" url:"sortOrder,omitempty"`
	// This is the maximum number of items to return. Defaults to 100.
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// This will return items where the createdAt is greater than the specified value.
	CreatedAtGt *time.Time `json:"-" url:"createdAtGt,omitempty"`
	// This will return items where the createdAt is less than the specified value.
	CreatedAtLt *time.Time `json:"-" url:"createdAtLt,omitempty"`
	// This will return items where the createdAt is greater than or equal to the specified value.
	CreatedAtGe *time.Time `json:"-" url:"createdAtGe,omitempty"`
	// This will return items where the createdAt is less than or equal to the specified value.
	CreatedAtLe *time.Time `json:"-" url:"createdAtLe,omitempty"`
	// This will return items where the updatedAt is greater than the specified value.
	UpdatedAtGt *time.Time `json:"-" url:"updatedAtGt,omitempty"`
	// This will return items where the updatedAt is less than the specified value.
	UpdatedAtLt *time.Time `json:"-" url:"updatedAtLt,omitempty"`
	// This will return items where the updatedAt is greater than or equal to the specified value.
	UpdatedAtGe *time.Time `json:"-" url:"updatedAtGe,omitempty"`
	// This will return items where the updatedAt is less than or equal to the specified value.
	UpdatedAtLe *time.Time `json:"-" url:"updatedAtLe,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSessionsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetName(name *string) {
	l.Name = name
	l.require(listSessionsRequestFieldName)
}

// SetAssistantId sets the AssistantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetAssistantId(assistantId *string) {
	l.AssistantId = assistantId
	l.require(listSessionsRequestFieldAssistantId)
}

// SetSquadId sets the SquadId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetSquadId(squadId *string) {
	l.SquadId = squadId
	l.require(listSessionsRequestFieldSquadId)
}

// SetWorkflowId sets the WorkflowId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetWorkflowId(workflowId *string) {
	l.WorkflowId = workflowId
	l.require(listSessionsRequestFieldWorkflowId)
}

// SetNumberE164CheckEnabled sets the NumberE164CheckEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetNumberE164CheckEnabled(numberE164CheckEnabled *bool) {
	l.NumberE164CheckEnabled = numberE164CheckEnabled
	l.require(listSessionsRequestFieldNumberE164CheckEnabled)
}

// SetExtension sets the Extension field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetExtension(extension *string) {
	l.Extension = extension
	l.require(listSessionsRequestFieldExtension)
}

// SetAssistantOverrides sets the AssistantOverrides field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetAssistantOverrides(assistantOverrides *string) {
	l.AssistantOverrides = assistantOverrides
	l.require(listSessionsRequestFieldAssistantOverrides)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetNumber(number *string) {
	l.Number = number
	l.require(listSessionsRequestFieldNumber)
}

// SetSipUri sets the SipUri field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetSipUri(sipUri *string) {
	l.SipUri = sipUri
	l.require(listSessionsRequestFieldSipUri)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetEmail(email *string) {
	l.Email = email
	l.require(listSessionsRequestFieldEmail)
}

// SetExternalId sets the ExternalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetExternalId(externalId *string) {
	l.ExternalId = externalId
	l.require(listSessionsRequestFieldExternalId)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetPage(page *float64) {
	l.Page = page
	l.require(listSessionsRequestFieldPage)
}

// SetSortOrder sets the SortOrder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetSortOrder(sortOrder *ListSessionsRequestSortOrder) {
	l.SortOrder = sortOrder
	l.require(listSessionsRequestFieldSortOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetLimit(limit *float64) {
	l.Limit = limit
	l.require(listSessionsRequestFieldLimit)
}

// SetCreatedAtGt sets the CreatedAtGt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetCreatedAtGt(createdAtGt *time.Time) {
	l.CreatedAtGt = createdAtGt
	l.require(listSessionsRequestFieldCreatedAtGt)
}

// SetCreatedAtLt sets the CreatedAtLt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetCreatedAtLt(createdAtLt *time.Time) {
	l.CreatedAtLt = createdAtLt
	l.require(listSessionsRequestFieldCreatedAtLt)
}

// SetCreatedAtGe sets the CreatedAtGe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetCreatedAtGe(createdAtGe *time.Time) {
	l.CreatedAtGe = createdAtGe
	l.require(listSessionsRequestFieldCreatedAtGe)
}

// SetCreatedAtLe sets the CreatedAtLe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetCreatedAtLe(createdAtLe *time.Time) {
	l.CreatedAtLe = createdAtLe
	l.require(listSessionsRequestFieldCreatedAtLe)
}

// SetUpdatedAtGt sets the UpdatedAtGt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetUpdatedAtGt(updatedAtGt *time.Time) {
	l.UpdatedAtGt = updatedAtGt
	l.require(listSessionsRequestFieldUpdatedAtGt)
}

// SetUpdatedAtLt sets the UpdatedAtLt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetUpdatedAtLt(updatedAtLt *time.Time) {
	l.UpdatedAtLt = updatedAtLt
	l.require(listSessionsRequestFieldUpdatedAtLt)
}

// SetUpdatedAtGe sets the UpdatedAtGe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetUpdatedAtGe(updatedAtGe *time.Time) {
	l.UpdatedAtGe = updatedAtGe
	l.require(listSessionsRequestFieldUpdatedAtGe)
}

// SetUpdatedAtLe sets the UpdatedAtLe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetUpdatedAtLe(updatedAtLe *time.Time) {
	l.UpdatedAtLe = updatedAtLe
	l.require(listSessionsRequestFieldUpdatedAtLe)
}

var (
	sessionFieldId                = big.NewInt(1 << 0)
	sessionFieldOrgId             = big.NewInt(1 << 1)
	sessionFieldCreatedAt         = big.NewInt(1 << 2)
	sessionFieldUpdatedAt         = big.NewInt(1 << 3)
	sessionFieldCost              = big.NewInt(1 << 4)
	sessionFieldCosts             = big.NewInt(1 << 5)
	sessionFieldName              = big.NewInt(1 << 6)
	sessionFieldStatus            = big.NewInt(1 << 7)
	sessionFieldExpirationSeconds = big.NewInt(1 << 8)
	sessionFieldAssistantId       = big.NewInt(1 << 9)
	sessionFieldAssistant         = big.NewInt(1 << 10)
	sessionFieldSquadId           = big.NewInt(1 << 11)
	sessionFieldSquad             = big.NewInt(1 << 12)
	sessionFieldMessages          = big.NewInt(1 << 13)
	sessionFieldCustomer          = big.NewInt(1 << 14)
	sessionFieldPhoneNumberId     = big.NewInt(1 << 15)
	sessionFieldPhoneNumber       = big.NewInt(1 << 16)
	sessionFieldArtifact          = big.NewInt(1 << 17)
)

type Session struct {
	// This is the unique identifier for the session.
	Id string `json:"id" url:"id"`
	// This is the unique identifier for the organization that owns this session.
	OrgId string `json:"orgId" url:"orgId"`
	// This is the ISO 8601 timestamp indicating when the session was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// This is the ISO 8601 timestamp indicating when the session was last updated.
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	// This is the cost of the session in USD.
	Cost *float64 `json:"cost,omitempty" url:"cost,omitempty"`
	// These are the costs of individual components of the session in USD.
	Costs []*SessionCostsItem `json:"costs,omitempty" url:"costs,omitempty"`
	// This is a user-defined name for the session. Maximum length is 40 characters.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// This is the current status of the session. Can be either 'active' or 'completed'.
	Status *SessionStatus `json:"status,omitempty" url:"status,omitempty"`
	// Session expiration time in seconds. Defaults to 24 hours (86400 seconds) if not set.
	ExpirationSeconds *float64 `json:"expirationSeconds,omitempty" url:"expirationSeconds,omitempty"`
	// This is the ID of the assistant associated with this session. Use this when referencing an existing assistant.
	AssistantId *string `json:"assistantId,omitempty" url:"assistantId,omitempty"`
	// This is the assistant configuration for this session. Use this when creating a new assistant configuration.
	// If assistantId is provided, this will be ignored.
	Assistant *CreateAssistantDto `json:"assistant,omitempty" url:"assistant,omitempty"`
	// This is the squad ID associated with this session. Use this when referencing an existing squad.
	SquadId *string `json:"squadId,omitempty" url:"squadId,omitempty"`
	// This is the squad configuration for this session. Use this when creating a new squad configuration.
	// If squadId is provided, this will be ignored.
	Squad *CreateSquadDto `json:"squad,omitempty" url:"squad,omitempty"`
	// This is an array of chat messages in the session.
	Messages []*SessionMessagesItem `json:"messages,omitempty" url:"messages,omitempty"`
	// This is the customer information associated with this session.
	Customer *CreateCustomerDto `json:"customer,omitempty" url:"customer,omitempty"`
	// This is the ID of the phone number associated with this session.
	PhoneNumberId *string `json:"phoneNumberId,omitempty" url:"phoneNumberId,omitempty"`
	// This is the phone number configuration for this session.
	PhoneNumber *ImportTwilioPhoneNumberDto `json:"phoneNumber,omitempty" url:"phoneNumber,omitempty"`
	// These are the artifacts that were extracted from the session messages.
	// They are only available after the session has completed.
	// The artifact plan from the assistant or active assistant of squad is used to generate the artifact.
	// Currently the only supported fields of assistant artifact plan are:
	// - structuredOutputIds
	Artifact *Artifact `json:"artifact,omitempty" url:"artifact,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Session) GetId() string {
	if s == nil {
		return ""
	}
	return s.Id
}

func (s *Session) GetOrgId() string {
	if s == nil {
		return ""
	}
	return s.OrgId
}

func (s *Session) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Session) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}

func (s *Session) GetCost() *float64 {
	if s == nil {
		return nil
	}
	return s.Cost
}

func (s *Session) GetCosts() []*SessionCostsItem {
	if s == nil {
		return nil
	}
	return s.Costs
}

func (s *Session) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *Session) GetStatus() *SessionStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *Session) GetExpirationSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.ExpirationSeconds
}

func (s *Session) GetAssistantId() *string {
	if s == nil {
		return nil
	}
	return s.AssistantId
}

func (s *Session) GetAssistant() *CreateAssistantDto {
	if s == nil {
		return nil
	}
	return s.Assistant
}

func (s *Session) GetSquadId() *string {
	if s == nil {
		return nil
	}
	return s.SquadId
}

func (s *Session) GetSquad() *CreateSquadDto {
	if s == nil {
		return nil
	}
	return s.Squad
}

func (s *Session) GetMessages() []*SessionMessagesItem {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *Session) GetCustomer() *CreateCustomerDto {
	if s == nil {
		return nil
	}
	return s.Customer
}

func (s *Session) GetPhoneNumberId() *string {
	if s == nil {
		return nil
	}
	return s.PhoneNumberId
}

func (s *Session) GetPhoneNumber() *ImportTwilioPhoneNumberDto {
	if s == nil {
		return nil
	}
	return s.PhoneNumber
}

func (s *Session) GetArtifact() *Artifact {
	if s == nil {
		return nil
	}
	return s.Artifact
}

func (s *Session) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *Session) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetId(id string) {
	s.Id = id
	s.require(sessionFieldId)
}

// SetOrgId sets the OrgId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetOrgId(orgId string) {
	s.OrgId = orgId
	s.require(sessionFieldOrgId)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetCreatedAt(createdAt time.Time) {
	s.CreatedAt = createdAt
	s.require(sessionFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetUpdatedAt(updatedAt time.Time) {
	s.UpdatedAt = updatedAt
	s.require(sessionFieldUpdatedAt)
}

// SetCost sets the Cost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetCost(cost *float64) {
	s.Cost = cost
	s.require(sessionFieldCost)
}

// SetCosts sets the Costs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetCosts(costs []*SessionCostsItem) {
	s.Costs = costs
	s.require(sessionFieldCosts)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetName(name *string) {
	s.Name = name
	s.require(sessionFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetStatus(status *SessionStatus) {
	s.Status = status
	s.require(sessionFieldStatus)
}

// SetExpirationSeconds sets the ExpirationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetExpirationSeconds(expirationSeconds *float64) {
	s.ExpirationSeconds = expirationSeconds
	s.require(sessionFieldExpirationSeconds)
}

// SetAssistantId sets the AssistantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetAssistantId(assistantId *string) {
	s.AssistantId = assistantId
	s.require(sessionFieldAssistantId)
}

// SetAssistant sets the Assistant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetAssistant(assistant *CreateAssistantDto) {
	s.Assistant = assistant
	s.require(sessionFieldAssistant)
}

// SetSquadId sets the SquadId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetSquadId(squadId *string) {
	s.SquadId = squadId
	s.require(sessionFieldSquadId)
}

// SetSquad sets the Squad field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetSquad(squad *CreateSquadDto) {
	s.Squad = squad
	s.require(sessionFieldSquad)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetMessages(messages []*SessionMessagesItem) {
	s.Messages = messages
	s.require(sessionFieldMessages)
}

// SetCustomer sets the Customer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetCustomer(customer *CreateCustomerDto) {
	s.Customer = customer
	s.require(sessionFieldCustomer)
}

// SetPhoneNumberId sets the PhoneNumberId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetPhoneNumberId(phoneNumberId *string) {
	s.PhoneNumberId = phoneNumberId
	s.require(sessionFieldPhoneNumberId)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetPhoneNumber(phoneNumber *ImportTwilioPhoneNumberDto) {
	s.PhoneNumber = phoneNumber
	s.require(sessionFieldPhoneNumber)
}

// SetArtifact sets the Artifact field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetArtifact(artifact *Artifact) {
	s.Artifact = artifact
	s.require(sessionFieldArtifact)
}

func (s *Session) UnmarshalJSON(data []byte) error {
	type embed Session
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = Session(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	s.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Session) MarshalJSON() ([]byte, error) {
	type embed Session
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*s),
		CreatedAt: internal.NewDateTime(s.CreatedAt),
		UpdatedAt: internal.NewDateTime(s.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *Session) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	sessionCostFieldType = big.NewInt(1 << 0)
	sessionCostFieldCost = big.NewInt(1 << 1)
)

type SessionCost struct {
	// This is the type of cost, always 'session' for this class.
	Type SessionCostType `json:"type" url:"type"`
	// This is the cost of the component in USD.
	Cost float64 `json:"cost" url:"cost"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SessionCost) GetType() SessionCostType {
	if s == nil {
		return ""
	}
	return s.Type
}

func (s *SessionCost) GetCost() float64 {
	if s == nil {
		return 0
	}
	return s.Cost
}

func (s *SessionCost) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SessionCost) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionCost) SetType(type_ SessionCostType) {
	s.Type = type_
	s.require(sessionCostFieldType)
}

// SetCost sets the Cost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionCost) SetCost(cost float64) {
	s.Cost = cost
	s.require(sessionCostFieldCost)
}

func (s *SessionCost) UnmarshalJSON(data []byte) error {
	type unmarshaler SessionCost
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SessionCost(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SessionCost) MarshalJSON() ([]byte, error) {
	type embed SessionCost
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SessionCost) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// This is the type of cost, always 'session' for this class.
type SessionCostType string

const (
	SessionCostTypeSession SessionCostType = "session"
)

func NewSessionCostTypeFromString(s string) (SessionCostType, error) {
	switch s {
	case "session":
		return SessionCostTypeSession, nil
	}
	var t SessionCostType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SessionCostType) Ptr() *SessionCostType {
	return &s
}

type SessionCostsItem struct {
	ModelCost    *ModelCost
	AnalysisCost *AnalysisCost
	SessionCost  *SessionCost

	typ string
}

func (s *SessionCostsItem) GetModelCost() *ModelCost {
	if s == nil {
		return nil
	}
	return s.ModelCost
}

func (s *SessionCostsItem) GetAnalysisCost() *AnalysisCost {
	if s == nil {
		return nil
	}
	return s.AnalysisCost
}

func (s *SessionCostsItem) GetSessionCost() *SessionCost {
	if s == nil {
		return nil
	}
	return s.SessionCost
}

func (s *SessionCostsItem) UnmarshalJSON(data []byte) error {
	valueModelCost := new(ModelCost)
	if err := json.Unmarshal(data, &valueModelCost); err == nil {
		s.typ = "ModelCost"
		s.ModelCost = valueModelCost
		return nil
	}
	valueAnalysisCost := new(AnalysisCost)
	if err := json.Unmarshal(data, &valueAnalysisCost); err == nil {
		s.typ = "AnalysisCost"
		s.AnalysisCost = valueAnalysisCost
		return nil
	}
	valueSessionCost := new(SessionCost)
	if err := json.Unmarshal(data, &valueSessionCost); err == nil {
		s.typ = "SessionCost"
		s.SessionCost = valueSessionCost
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, s)
}

func (s SessionCostsItem) MarshalJSON() ([]byte, error) {
	if s.typ == "ModelCost" || s.ModelCost != nil {
		return json.Marshal(s.ModelCost)
	}
	if s.typ == "AnalysisCost" || s.AnalysisCost != nil {
		return json.Marshal(s.AnalysisCost)
	}
	if s.typ == "SessionCost" || s.SessionCost != nil {
		return json.Marshal(s.SessionCost)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", s)
}

type SessionCostsItemVisitor interface {
	VisitModelCost(*ModelCost) error
	VisitAnalysisCost(*AnalysisCost) error
	VisitSessionCost(*SessionCost) error
}

func (s *SessionCostsItem) Accept(visitor SessionCostsItemVisitor) error {
	if s.typ == "ModelCost" || s.ModelCost != nil {
		return visitor.VisitModelCost(s.ModelCost)
	}
	if s.typ == "AnalysisCost" || s.AnalysisCost != nil {
		return visitor.VisitAnalysisCost(s.AnalysisCost)
	}
	if s.typ == "SessionCost" || s.SessionCost != nil {
		return visitor.VisitSessionCost(s.SessionCost)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", s)
}

type SessionMessagesItem struct {
	SystemMessage    *SystemMessage
	UserMessage      *UserMessage
	AssistantMessage *AssistantMessage
	ToolMessage      *ToolMessage
	DeveloperMessage *DeveloperMessage

	typ string
}

func (s *SessionMessagesItem) GetSystemMessage() *SystemMessage {
	if s == nil {
		return nil
	}
	return s.SystemMessage
}

func (s *SessionMessagesItem) GetUserMessage() *UserMessage {
	if s == nil {
		return nil
	}
	return s.UserMessage
}

func (s *SessionMessagesItem) GetAssistantMessage() *AssistantMessage {
	if s == nil {
		return nil
	}
	return s.AssistantMessage
}

func (s *SessionMessagesItem) GetToolMessage() *ToolMessage {
	if s == nil {
		return nil
	}
	return s.ToolMessage
}

func (s *SessionMessagesItem) GetDeveloperMessage() *DeveloperMessage {
	if s == nil {
		return nil
	}
	return s.DeveloperMessage
}

func (s *SessionMessagesItem) UnmarshalJSON(data []byte) error {
	valueSystemMessage := new(SystemMessage)
	if err := json.Unmarshal(data, &valueSystemMessage); err == nil {
		s.typ = "SystemMessage"
		s.SystemMessage = valueSystemMessage
		return nil
	}
	valueUserMessage := new(UserMessage)
	if err := json.Unmarshal(data, &valueUserMessage); err == nil {
		s.typ = "UserMessage"
		s.UserMessage = valueUserMessage
		return nil
	}
	valueAssistantMessage := new(AssistantMessage)
	if err := json.Unmarshal(data, &valueAssistantMessage); err == nil {
		s.typ = "AssistantMessage"
		s.AssistantMessage = valueAssistantMessage
		return nil
	}
	valueToolMessage := new(ToolMessage)
	if err := json.Unmarshal(data, &valueToolMessage); err == nil {
		s.typ = "ToolMessage"
		s.ToolMessage = valueToolMessage
		return nil
	}
	valueDeveloperMessage := new(DeveloperMessage)
	if err := json.Unmarshal(data, &valueDeveloperMessage); err == nil {
		s.typ = "DeveloperMessage"
		s.DeveloperMessage = valueDeveloperMessage
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, s)
}

func (s SessionMessagesItem) MarshalJSON() ([]byte, error) {
	if s.typ == "SystemMessage" || s.SystemMessage != nil {
		return json.Marshal(s.SystemMessage)
	}
	if s.typ == "UserMessage" || s.UserMessage != nil {
		return json.Marshal(s.UserMessage)
	}
	if s.typ == "AssistantMessage" || s.AssistantMessage != nil {
		return json.Marshal(s.AssistantMessage)
	}
	if s.typ == "ToolMessage" || s.ToolMessage != nil {
		return json.Marshal(s.ToolMessage)
	}
	if s.typ == "DeveloperMessage" || s.DeveloperMessage != nil {
		return json.Marshal(s.DeveloperMessage)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", s)
}

type SessionMessagesItemVisitor interface {
	VisitSystemMessage(*SystemMessage) error
	VisitUserMessage(*UserMessage) error
	VisitAssistantMessage(*AssistantMessage) error
	VisitToolMessage(*ToolMessage) error
	VisitDeveloperMessage(*DeveloperMessage) error
}

func (s *SessionMessagesItem) Accept(visitor SessionMessagesItemVisitor) error {
	if s.typ == "SystemMessage" || s.SystemMessage != nil {
		return visitor.VisitSystemMessage(s.SystemMessage)
	}
	if s.typ == "UserMessage" || s.UserMessage != nil {
		return visitor.VisitUserMessage(s.UserMessage)
	}
	if s.typ == "AssistantMessage" || s.AssistantMessage != nil {
		return visitor.VisitAssistantMessage(s.AssistantMessage)
	}
	if s.typ == "ToolMessage" || s.ToolMessage != nil {
		return visitor.VisitToolMessage(s.ToolMessage)
	}
	if s.typ == "DeveloperMessage" || s.DeveloperMessage != nil {
		return visitor.VisitDeveloperMessage(s.DeveloperMessage)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", s)
}

var (
	sessionPaginatedResponseFieldResults  = big.NewInt(1 << 0)
	sessionPaginatedResponseFieldMetadata = big.NewInt(1 << 1)
)

type SessionPaginatedResponse struct {
	Results  []*Session      `json:"results" url:"results"`
	Metadata *PaginationMeta `json:"metadata" url:"metadata"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SessionPaginatedResponse) GetResults() []*Session {
	if s == nil {
		return nil
	}
	return s.Results
}

func (s *SessionPaginatedResponse) GetMetadata() *PaginationMeta {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SessionPaginatedResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SessionPaginatedResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionPaginatedResponse) SetResults(results []*Session) {
	s.Results = results
	s.require(sessionPaginatedResponseFieldResults)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionPaginatedResponse) SetMetadata(metadata *PaginationMeta) {
	s.Metadata = metadata
	s.require(sessionPaginatedResponseFieldMetadata)
}

func (s *SessionPaginatedResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SessionPaginatedResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SessionPaginatedResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SessionPaginatedResponse) MarshalJSON() ([]byte, error) {
	type embed SessionPaginatedResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SessionPaginatedResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// This is the current status of the session. Can be either 'active' or 'completed'.
type SessionStatus string

const (
	SessionStatusActive    SessionStatus = "active"
	SessionStatusCompleted SessionStatus = "completed"
)

func NewSessionStatusFromString(s string) (SessionStatus, error) {
	switch s {
	case "active":
		return SessionStatusActive, nil
	case "completed":
		return SessionStatusCompleted, nil
	}
	var t SessionStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SessionStatus) Ptr() *SessionStatus {
	return &s
}

type CreateSessionDtoMessagesItem struct {
	SystemMessage    *SystemMessage
	UserMessage      *UserMessage
	AssistantMessage *AssistantMessage
	ToolMessage      *ToolMessage
	DeveloperMessage *DeveloperMessage

	typ string
}

func (c *CreateSessionDtoMessagesItem) GetSystemMessage() *SystemMessage {
	if c == nil {
		return nil
	}
	return c.SystemMessage
}

func (c *CreateSessionDtoMessagesItem) GetUserMessage() *UserMessage {
	if c == nil {
		return nil
	}
	return c.UserMessage
}

func (c *CreateSessionDtoMessagesItem) GetAssistantMessage() *AssistantMessage {
	if c == nil {
		return nil
	}
	return c.AssistantMessage
}

func (c *CreateSessionDtoMessagesItem) GetToolMessage() *ToolMessage {
	if c == nil {
		return nil
	}
	return c.ToolMessage
}

func (c *CreateSessionDtoMessagesItem) GetDeveloperMessage() *DeveloperMessage {
	if c == nil {
		return nil
	}
	return c.DeveloperMessage
}

func (c *CreateSessionDtoMessagesItem) UnmarshalJSON(data []byte) error {
	valueSystemMessage := new(SystemMessage)
	if err := json.Unmarshal(data, &valueSystemMessage); err == nil {
		c.typ = "SystemMessage"
		c.SystemMessage = valueSystemMessage
		return nil
	}
	valueUserMessage := new(UserMessage)
	if err := json.Unmarshal(data, &valueUserMessage); err == nil {
		c.typ = "UserMessage"
		c.UserMessage = valueUserMessage
		return nil
	}
	valueAssistantMessage := new(AssistantMessage)
	if err := json.Unmarshal(data, &valueAssistantMessage); err == nil {
		c.typ = "AssistantMessage"
		c.AssistantMessage = valueAssistantMessage
		return nil
	}
	valueToolMessage := new(ToolMessage)
	if err := json.Unmarshal(data, &valueToolMessage); err == nil {
		c.typ = "ToolMessage"
		c.ToolMessage = valueToolMessage
		return nil
	}
	valueDeveloperMessage := new(DeveloperMessage)
	if err := json.Unmarshal(data, &valueDeveloperMessage); err == nil {
		c.typ = "DeveloperMessage"
		c.DeveloperMessage = valueDeveloperMessage
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, c)
}

func (c CreateSessionDtoMessagesItem) MarshalJSON() ([]byte, error) {
	if c.typ == "SystemMessage" || c.SystemMessage != nil {
		return json.Marshal(c.SystemMessage)
	}
	if c.typ == "UserMessage" || c.UserMessage != nil {
		return json.Marshal(c.UserMessage)
	}
	if c.typ == "AssistantMessage" || c.AssistantMessage != nil {
		return json.Marshal(c.AssistantMessage)
	}
	if c.typ == "ToolMessage" || c.ToolMessage != nil {
		return json.Marshal(c.ToolMessage)
	}
	if c.typ == "DeveloperMessage" || c.DeveloperMessage != nil {
		return json.Marshal(c.DeveloperMessage)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", c)
}

type CreateSessionDtoMessagesItemVisitor interface {
	VisitSystemMessage(*SystemMessage) error
	VisitUserMessage(*UserMessage) error
	VisitAssistantMessage(*AssistantMessage) error
	VisitToolMessage(*ToolMessage) error
	VisitDeveloperMessage(*DeveloperMessage) error
}

func (c *CreateSessionDtoMessagesItem) Accept(visitor CreateSessionDtoMessagesItemVisitor) error {
	if c.typ == "SystemMessage" || c.SystemMessage != nil {
		return visitor.VisitSystemMessage(c.SystemMessage)
	}
	if c.typ == "UserMessage" || c.UserMessage != nil {
		return visitor.VisitUserMessage(c.UserMessage)
	}
	if c.typ == "AssistantMessage" || c.AssistantMessage != nil {
		return visitor.VisitAssistantMessage(c.AssistantMessage)
	}
	if c.typ == "ToolMessage" || c.ToolMessage != nil {
		return visitor.VisitToolMessage(c.ToolMessage)
	}
	if c.typ == "DeveloperMessage" || c.DeveloperMessage != nil {
		return visitor.VisitDeveloperMessage(c.DeveloperMessage)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", c)
}

// This is the current status of the session. Can be either 'active' or 'completed'.
type CreateSessionDtoStatus string

const (
	CreateSessionDtoStatusActive    CreateSessionDtoStatus = "active"
	CreateSessionDtoStatusCompleted CreateSessionDtoStatus = "completed"
)

func NewCreateSessionDtoStatusFromString(s string) (CreateSessionDtoStatus, error) {
	switch s {
	case "active":
		return CreateSessionDtoStatusActive, nil
	case "completed":
		return CreateSessionDtoStatusCompleted, nil
	}
	var t CreateSessionDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSessionDtoStatus) Ptr() *CreateSessionDtoStatus {
	return &c
}

type ListSessionsRequestSortOrder string

const (
	ListSessionsRequestSortOrderAsc  ListSessionsRequestSortOrder = "ASC"
	ListSessionsRequestSortOrderDesc ListSessionsRequestSortOrder = "DESC"
)

func NewListSessionsRequestSortOrderFromString(s string) (ListSessionsRequestSortOrder, error) {
	switch s {
	case "ASC":
		return ListSessionsRequestSortOrderAsc, nil
	case "DESC":
		return ListSessionsRequestSortOrderDesc, nil
	}
	var t ListSessionsRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListSessionsRequestSortOrder) Ptr() *ListSessionsRequestSortOrder {
	return &l
}

type UpdateSessionDtoMessagesItem struct {
	SystemMessage    *SystemMessage
	UserMessage      *UserMessage
	AssistantMessage *AssistantMessage
	ToolMessage      *ToolMessage
	DeveloperMessage *DeveloperMessage

	typ string
}

func (u *UpdateSessionDtoMessagesItem) GetSystemMessage() *SystemMessage {
	if u == nil {
		return nil
	}
	return u.SystemMessage
}

func (u *UpdateSessionDtoMessagesItem) GetUserMessage() *UserMessage {
	if u == nil {
		return nil
	}
	return u.UserMessage
}

func (u *UpdateSessionDtoMessagesItem) GetAssistantMessage() *AssistantMessage {
	if u == nil {
		return nil
	}
	return u.AssistantMessage
}

func (u *UpdateSessionDtoMessagesItem) GetToolMessage() *ToolMessage {
	if u == nil {
		return nil
	}
	return u.ToolMessage
}

func (u *UpdateSessionDtoMessagesItem) GetDeveloperMessage() *DeveloperMessage {
	if u == nil {
		return nil
	}
	return u.DeveloperMessage
}

func (u *UpdateSessionDtoMessagesItem) UnmarshalJSON(data []byte) error {
	valueSystemMessage := new(SystemMessage)
	if err := json.Unmarshal(data, &valueSystemMessage); err == nil {
		u.typ = "SystemMessage"
		u.SystemMessage = valueSystemMessage
		return nil
	}
	valueUserMessage := new(UserMessage)
	if err := json.Unmarshal(data, &valueUserMessage); err == nil {
		u.typ = "UserMessage"
		u.UserMessage = valueUserMessage
		return nil
	}
	valueAssistantMessage := new(AssistantMessage)
	if err := json.Unmarshal(data, &valueAssistantMessage); err == nil {
		u.typ = "AssistantMessage"
		u.AssistantMessage = valueAssistantMessage
		return nil
	}
	valueToolMessage := new(ToolMessage)
	if err := json.Unmarshal(data, &valueToolMessage); err == nil {
		u.typ = "ToolMessage"
		u.ToolMessage = valueToolMessage
		return nil
	}
	valueDeveloperMessage := new(DeveloperMessage)
	if err := json.Unmarshal(data, &valueDeveloperMessage); err == nil {
		u.typ = "DeveloperMessage"
		u.DeveloperMessage = valueDeveloperMessage
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateSessionDtoMessagesItem) MarshalJSON() ([]byte, error) {
	if u.typ == "SystemMessage" || u.SystemMessage != nil {
		return json.Marshal(u.SystemMessage)
	}
	if u.typ == "UserMessage" || u.UserMessage != nil {
		return json.Marshal(u.UserMessage)
	}
	if u.typ == "AssistantMessage" || u.AssistantMessage != nil {
		return json.Marshal(u.AssistantMessage)
	}
	if u.typ == "ToolMessage" || u.ToolMessage != nil {
		return json.Marshal(u.ToolMessage)
	}
	if u.typ == "DeveloperMessage" || u.DeveloperMessage != nil {
		return json.Marshal(u.DeveloperMessage)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateSessionDtoMessagesItemVisitor interface {
	VisitSystemMessage(*SystemMessage) error
	VisitUserMessage(*UserMessage) error
	VisitAssistantMessage(*AssistantMessage) error
	VisitToolMessage(*ToolMessage) error
	VisitDeveloperMessage(*DeveloperMessage) error
}

func (u *UpdateSessionDtoMessagesItem) Accept(visitor UpdateSessionDtoMessagesItemVisitor) error {
	if u.typ == "SystemMessage" || u.SystemMessage != nil {
		return visitor.VisitSystemMessage(u.SystemMessage)
	}
	if u.typ == "UserMessage" || u.UserMessage != nil {
		return visitor.VisitUserMessage(u.UserMessage)
	}
	if u.typ == "AssistantMessage" || u.AssistantMessage != nil {
		return visitor.VisitAssistantMessage(u.AssistantMessage)
	}
	if u.typ == "ToolMessage" || u.ToolMessage != nil {
		return visitor.VisitToolMessage(u.ToolMessage)
	}
	if u.typ == "DeveloperMessage" || u.DeveloperMessage != nil {
		return visitor.VisitDeveloperMessage(u.DeveloperMessage)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

// This is the new status for the session.
type UpdateSessionDtoStatus string

const (
	UpdateSessionDtoStatusActive    UpdateSessionDtoStatus = "active"
	UpdateSessionDtoStatusCompleted UpdateSessionDtoStatus = "completed"
)

func NewUpdateSessionDtoStatusFromString(s string) (UpdateSessionDtoStatus, error) {
	switch s {
	case "active":
		return UpdateSessionDtoStatusActive, nil
	case "completed":
		return UpdateSessionDtoStatusCompleted, nil
	}
	var t UpdateSessionDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateSessionDtoStatus) Ptr() *UpdateSessionDtoStatus {
	return &u
}

var (
	updateSessionDtoFieldId                = big.NewInt(1 << 0)
	updateSessionDtoFieldName              = big.NewInt(1 << 1)
	updateSessionDtoFieldStatus            = big.NewInt(1 << 2)
	updateSessionDtoFieldExpirationSeconds = big.NewInt(1 << 3)
	updateSessionDtoFieldMessages          = big.NewInt(1 << 4)
)

type UpdateSessionDto struct {
	Id string `json:"-" url:"-"`
	// This is the new name for the session. Maximum length is 40 characters.
	Name *string `json:"name,omitempty" url:"-"`
	// This is the new status for the session.
	Status *UpdateSessionDtoStatus `json:"status,omitempty" url:"-"`
	// Session expiration time in seconds. Defaults to 24 hours (86400 seconds) if not set.
	ExpirationSeconds *float64 `json:"expirationSeconds,omitempty" url:"-"`
	// This is the updated array of chat messages.
	Messages []*UpdateSessionDtoMessagesItem `json:"messages,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateSessionDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSessionDto) SetId(id string) {
	u.Id = id
	u.require(updateSessionDtoFieldId)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSessionDto) SetName(name *string) {
	u.Name = name
	u.require(updateSessionDtoFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSessionDto) SetStatus(status *UpdateSessionDtoStatus) {
	u.Status = status
	u.require(updateSessionDtoFieldStatus)
}

// SetExpirationSeconds sets the ExpirationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSessionDto) SetExpirationSeconds(expirationSeconds *float64) {
	u.ExpirationSeconds = expirationSeconds
	u.require(updateSessionDtoFieldExpirationSeconds)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSessionDto) SetMessages(messages []*UpdateSessionDtoMessagesItem) {
	u.Messages = messages
	u.require(updateSessionDtoFieldMessages)
}
