// Code generated by Fern. DO NOT EDIT.

package structuredoutputs

import (
	context "context"
	v505 "github.com/itrn0/server-sdk-go"
	core "github.com/itrn0/server-sdk-go/core"
	internal "github.com/itrn0/server-sdk-go/internal"
	option "github.com/itrn0/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) StructuredOutputControllerFindAll(
	ctx context.Context,
	request *v505.StructuredOutputControllerFindAllRequest,
	opts ...option.RequestOption,
) (*v505.StructuredOutputPaginatedResponse, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerFindAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerCreate(
	ctx context.Context,
	request *v505.CreateStructuredOutputDto,
	opts ...option.RequestOption,
) (*v505.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerFindOne(
	ctx context.Context,
	request *v505.StructuredOutputControllerFindOneRequest,
	opts ...option.RequestOption,
) (*v505.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerFindOne(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerRemove(
	ctx context.Context,
	request *v505.StructuredOutputControllerRemoveRequest,
	opts ...option.RequestOption,
) (*v505.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerRemove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerUpdate(
	ctx context.Context,
	request *v505.UpdateStructuredOutputDto,
	opts ...option.RequestOption,
) (*v505.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerRun(
	ctx context.Context,
	request *v505.StructuredOutputRunDto,
	opts ...option.RequestOption,
) (*v505.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerRun(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Analyzes assistant configuration and generates contextual structured output recommendations
func (c *Client) StructuredOutputControllerSuggest(
	ctx context.Context,
	request *v505.GenerateStructuredOutputSuggestionsDto,
	opts ...option.RequestOption,
) ([]map[string]any, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerSuggest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
