// Code generated by Fern. DO NOT EDIT.

package providerresources

import (
	context "context"
	v505 "github.com/itrn0/server-sdk-go"
	core "github.com/itrn0/server-sdk-go/core"
	internal "github.com/itrn0/server-sdk-go/internal"
	option "github.com/itrn0/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ProviderResourceControllerGetProviderResourcesPaginated(
	ctx context.Context,
	request *v505.ProviderResourceControllerGetProviderResourcesPaginatedRequest,
	opts ...option.RequestOption,
) (*v505.ProviderResourcePaginatedResponse, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerGetProviderResourcesPaginated(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerCreateProviderResource(
	ctx context.Context,
	request *v505.ProviderResourceControllerCreateProviderResourceRequest,
	opts ...option.RequestOption,
) (*v505.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerCreateProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerGetProviderResource(
	ctx context.Context,
	request *v505.ProviderResourceControllerGetProviderResourceRequest,
	opts ...option.RequestOption,
) (*v505.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerGetProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerDeleteProviderResource(
	ctx context.Context,
	request *v505.ProviderResourceControllerDeleteProviderResourceRequest,
	opts ...option.RequestOption,
) (*v505.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerDeleteProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerUpdateProviderResource(
	ctx context.Context,
	request *v505.ProviderResourceControllerUpdateProviderResourceRequest,
	opts ...option.RequestOption,
) (*v505.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerUpdateProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
