// Code generated by Fern. DO NOT EDIT.

package campaigns

import (
	context "context"
	v505 "github.com/itrn0/server-sdk-go"
	core "github.com/itrn0/server-sdk-go/core"
	internal "github.com/itrn0/server-sdk-go/internal"
	option "github.com/itrn0/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) CampaignControllerFindAll(
	ctx context.Context,
	request *v505.CampaignControllerFindAllRequest,
	opts ...option.RequestOption,
) (*v505.CampaignPaginatedResponse, error) {
	response, err := c.WithRawResponse.CampaignControllerFindAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CampaignControllerCreate(
	ctx context.Context,
	request *v505.CreateCampaignDto,
	opts ...option.RequestOption,
) (*v505.Campaign, error) {
	response, err := c.WithRawResponse.CampaignControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CampaignControllerFindOne(
	ctx context.Context,
	request *v505.CampaignControllerFindOneRequest,
	opts ...option.RequestOption,
) (*v505.Campaign, error) {
	response, err := c.WithRawResponse.CampaignControllerFindOne(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CampaignControllerRemove(
	ctx context.Context,
	request *v505.CampaignControllerRemoveRequest,
	opts ...option.RequestOption,
) (*v505.Campaign, error) {
	response, err := c.WithRawResponse.CampaignControllerRemove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CampaignControllerUpdate(
	ctx context.Context,
	request *v505.UpdateCampaignDto,
	opts ...option.RequestOption,
) (*v505.Campaign, error) {
	response, err := c.WithRawResponse.CampaignControllerUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
