// Code generated by Fern. DO NOT EDIT.

package insight

import (
	context "context"
	v505 "github.com/itrn0/server-sdk-go"
	core "github.com/itrn0/server-sdk-go/core"
	internal "github.com/itrn0/server-sdk-go/internal"
	option "github.com/itrn0/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) InsightControllerFindAll(
	ctx context.Context,
	request *v505.InsightControllerFindAllRequest,
	opts ...option.RequestOption,
) (*v505.InsightPaginatedResponse, error) {
	response, err := c.WithRawResponse.InsightControllerFindAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsightControllerCreate(
	ctx context.Context,
	request *v505.InsightControllerCreateRequest,
	opts ...option.RequestOption,
) (*v505.InsightControllerCreateResponse, error) {
	response, err := c.WithRawResponse.InsightControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsightControllerFindOne(
	ctx context.Context,
	request *v505.InsightControllerFindOneRequest,
	opts ...option.RequestOption,
) (*v505.InsightControllerFindOneResponse, error) {
	response, err := c.WithRawResponse.InsightControllerFindOne(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsightControllerRemove(
	ctx context.Context,
	request *v505.InsightControllerRemoveRequest,
	opts ...option.RequestOption,
) (*v505.InsightControllerRemoveResponse, error) {
	response, err := c.WithRawResponse.InsightControllerRemove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsightControllerUpdate(
	ctx context.Context,
	request *v505.InsightControllerUpdateRequest,
	opts ...option.RequestOption,
) (*v505.InsightControllerUpdateResponse, error) {
	response, err := c.WithRawResponse.InsightControllerUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsightControllerRun(
	ctx context.Context,
	request *v505.InsightRunDto,
	opts ...option.RequestOption,
) (*v505.InsightRunResponse, error) {
	response, err := c.WithRawResponse.InsightControllerRun(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) InsightControllerPreview(
	ctx context.Context,
	request *v505.InsightControllerPreviewRequest,
	opts ...option.RequestOption,
) (*v505.InsightRunResponse, error) {
	response, err := c.WithRawResponse.InsightControllerPreview(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
